### ISSUE TITLE
Spawner issue in 1.19

### ISSUE THREAD

**Issue by nivcoo** [BG-Software-LLC/WildStacker#567] opened 2022-07-31 12:19 UTC
### Minecraft's Version

1.19

### Plugin's Version

b323

### Describe the bug

Hello when i place spawner it became pig spawner like my video https://pics.revolis.fr/2022/07/31/14-18_QOjA.mp4 .

### To Reproduce

Place spawner and try to stack them.

**Comment by OmerBenGera** [comment] 2022-08-02 13:22
Duplicate of #556

**Closed by OmerBenGera** 2022-08-02 13:22 UTC
Labels: Pending
