### ISSUE TITLE
PreSpawnerSpawnEvent 

### ISSUE THREAD

**Issue by bpx573** [BG-Software-LLC/WildStacker#370] opened 2021-11-06 19:34 UTC
### Minecraft's Version

1.17.1

### Plugin's Version

3.6.1

### Describe the bug

The plugin has errors in console and doesn't stack spawners but does everything else.

### To Reproduce

Have a void world and try to stack the spawners. 

### Additional Information

https://pastebin.com/JA6CFRFb

**Comment by OmerBenGera** [comment] 2021-11-07 04:56
Send me your exact output of `/version` and `/version WildStacker` please.

**Comment by bpx573** [comment] 2021-11-07 18:49
/version: https://gyazo.com/9e397443e3ad65b2112f2321abdee53f
/version WildStacker: https://gyazo.com/d2371b080f13934b02942e90cf76e288

**Comment by OmerBenGera** [comment] 2021-11-07 21:41
Does it occur when using Paper?

**Comment by OmerBenGera** [comment] 2021-11-08 07:11
This was confirmed to be an issue with Purpur, I believe Airplane needs to update and then it will be fixed.
Duplicate of #367

**Closed by OmerBenGera** 2021-11-08 07:11 UTC
Labels: ❌ Unconfirmed
