### ISSUE TITLE
Dupe issue when daily restart

### ISSUE THREAD

**Issue by ArefyNetwork** [BG-Software-LLC/WildStacker#212] opened 2021-07-03 09:45 UTC
**Minecraft's Version**
1.8.8 paperspigot

**Plugin's Version**: -
WildStacker-b155.jar

**Describe the bug**
Dupe bug, before server restarts "some minutes before the daily restart", you've to pick up your spawners and then wait after the daily restart, on the video example user picked up all his spawners, and after the daily reset spawner had x145 spawners and he had the spawners on his inventory too. It's something about database, it doesn't save when /stop is used

**To Reproduce**
Mentioned in "describe the bug"

**Additional information**
Step 1 - https://www.youtube.com/watch?v=251CNsJIUFc
Step 2 - https://www.youtube.com/watch?v=6vgjPxrz71g

**Comment by OmerBenGera** [comment] 2021-07-03 09:59
Seems like your database is not saved correctly.
Look for errors and find the cause of that.

**Comment by ArefyNetwork** [comment] 2021-07-03 10:09
> Seems like your database is not saved correctly.
> Look for errors and find the cause of that.

Hello Ome, wildstacker doesn't seems to paste any error, only superiorskyblock: https://pastebin.com/Tu49XLFF

Also, /stop is used on daily restarts, it doesn't have anything to do if I use /stop than /restart right?

**Comment by ArefyNetwork** [comment] 2021-07-03 10:28
Maybe a command to save spawners into the database will help to add it into daily restart plugin commands, as /stacker save only saves items/mobs

**Comment by OmerBenGera** [comment] 2021-07-03 10:29
> 
> 
> Maybe a command to save spawners into the database will help to add it into daily restart plugin commands, as /stacker save only saves items/mobs

Spawners are saved once they are modified, therefore a "save" command is useless

**Comment by ArefyNetwork** [comment] 2021-07-03 10:32
> > Maybe a command to save spawners into the database will help to add it into daily restart plugin commands, as /stacker save only saves items/mobs
> 
> Spawners are saved once they are modified, therefore a "save" command is useless

So why when I use /stop after a spawner has being modified it doesn't save? It's weird :S

**Comment by ArefyNetwork** [comment] 2021-07-03 10:55
I've tested it on a server with only these plugins: https://i.gyazo.com/9b1e6fa3d00bd5b511d8f2ececcb7a96.png

And dupe still works, using same paperspigot 1.8.8, and default wildstacker config:

- https://www.youtube.com/watch?v=5hlbGVZHxLM

**Comment by OmerBenGera** [comment] 2021-07-03 11:35
Fixed in latest dev build (156)

**Closed by OmerBenGera** 2021-07-03 11:35 UTC
Labels: Bug Report, Confirmed
