### ISSUE TITLE
Incompatibility error with WildChests

### ISSUE THREAD

**Issue by Rubenicos** [BG-Software-LLC/WildStacker#901] opened 2024-03-21 15:44 UTC
### Minecraft's Version

1.20.4 

### Plugin's Version

2023.3-b40

### Describe the bug

Chest linking from WildChests executes `LinkedChestInteractEvent`, while WildStacker only detects the literal class `PlayerInteractEvent` at ItemUtils
https://github.com/BG-Software-LLC/WildStacker/blob/b2336b168b7ae370dc7828cbb2d7c80e7702feda/src/main/java/com/bgsoftware/wildstacker/utils/items/ItemUtils.java#L269-L279

### To Reproduce

Put WildStacker and WildChests in the same server and try to link a chest with `/chests link` command from WildChests

### Additional Information

<details>
<summary>Console logs (Click to see)</summary>
<pre>
[10:39:21 ERROR]: Could not pass event LinkedChestInteractEvent to WildStacker v2023.3-b40
java.lang.IllegalArgumentException: Cannot get used hand for event: class com.bgsoftware.wildchests.utils.LinkedChestInteractEvent
        at com.bgsoftware.wildstacker.utils.items.ItemUtils.getHand(ItemUtils.java:278) ~[WildStacker-2023.3-b40.jar:?]
        at com.bgsoftware.wildstacker.utils.items.ItemUtils.isOffHand(ItemUtils.java:359) ~[WildStacker-2023.3-b40.jar:?]
        at com.bgsoftware.wildstacker.listeners.ToolsListener.onBlockSimulate(ToolsListener.java:100) ~[WildStacker-2023.3-b40.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor530.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[?:git-UniverseSpigot-"29224da"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[?:git-UniverseSpigot-"29224da"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[?:git-UniverseSpigot-"29224da"]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:58) ~[?:git-UniverseSpigot-"29224da"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[?:git-UniverseSpigot-"29224da"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[?:git-UniverseSpigot-"29224da"]
        at com.bgsoftware.wildchests.command.commands.CommandLink.perform(CommandLink.java:91) ~[WildChests-2023.3-b33.jar:?]
        at com.bgsoftware.wildchests.command.CommandsHandler.onCommand(CommandsHandler.java:47) ~[WildChests-2023.3-b33.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[?:git-UniverseSpigot-"29224da"]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:150) ~[?:git-UniverseSpigot-"29224da"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:1002) ~[?:git-UniverseSpigot-"29224da"]
        at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[?:git-UniverseSpigot-"29224da"]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:32) ~[?:git-UniverseSpigot-"29224da"]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[?:git-UniverseSpigot-"29224da"]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[?:git-UniverseSpigot-"29224da"]
        at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5) ~[?:git-UniverseSpigot-"29224da"]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:101) ~[?:git-UniverseSpigot-"29224da"]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:443) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:345) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:332) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2249) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2209) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:58) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[?:git-UniverseSpigot-"29224da"]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:152) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1464) ~[?:git-UniverseSpigot-"29224da"]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[?:git-UniverseSpigot-"29224da"]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1441) ~[?:git-UniverseSpigot-"29224da"]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1369) ~[?:git-UniverseSpigot-"29224da"]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1347) ~[?:git-UniverseSpigot-"29224da"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1236) ~[?:git-UniverseSpigot-"29224da"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:324) ~[?:git-UniverseSpigot-"29224da"]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
</pre>
</details>

**Comment by OmerBenGera** [comment] 2024-03-30 12:44
Duplicate of #898

**Closed by OmerBenGera** 2024-03-30 12:44 UTC
Labels: Pending
