### ISSUE TITLE
Server crashes

### ISSUE THREAD

**Issue by Sckaletz** [BG-Software-LLC/WildStacker#854] opened 2023-09-27 20:58 UTC
### Minecraft's Version

This server is running Paper version git-Paper-171 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 33bec7f)

### Plugin's Version

[WildStacker] Loading server plugin WildStacker v2023.2-b19

### Describe the bug

When a player holds wheat (in this case with cows) to attract their attention and get them to follow him, and he then drops the wheat when they are all beneath him, the stacking of the cows is removed and all cows are turned into single cows again, crashing the server. I have no idea if this has something to do with cramming or whatever it's called.

Video: https://youtu.be/W_E2xv9eAD4 (I had to make a few clips to actually show the effect)
Logs: https://pastebin.com/B02XKrtn

### To Reproduce

Cramp large stacks of animals together and - in this case - drop the wheat.

**Comment by OmerBenGera** [comment] 2023-09-29 16:16
I think it something to do with mob spawning by spawners
Are you able to replicate the issue on a smaller setup, and narrow down to exactly what the issue is?

Also, please upload your config to pastebin and send a link to it here

**Comment by Sckaletz** [comment] 2023-09-29 16:41
Ok here's the config: https://pastebin.com/F8a4snX4

**Comment by Sckaletz** [comment] 2023-10-14 16:07
I haven't been able to reproduce it on another setup, but I have no clue what to do to reproduce it. It clearly has something to do with the spawners trying to spawn something. 
All I know is that our server crashes every two hours or so. This is the latest log from a few hours ago.

https://pastebin.com/6L1if6Ke

**Comment by Sckaletz** [comment] 2023-10-14 17:25
Ok some more info. I think I've figured it out now.

It's the effect that comes when mobs spawn from the spawner. In this case where the stack of spawners is pretty high (obs. I have particles disabled). I use to have a limit of 50 entities in a chunk and that would crash the server instantly like you see in this first video. In this video the server is crashing as soon as I join the chunk:
https://medal.tv/games/minecraft/clips/1yC0HMeiVVcf0x/d1337tqAyfWA?invite=cr-MSxHNWYsNzM1MDU0Myw

Here I have a limit of 15 entities:
https://medal.tv/games/minecraft/clips/1yC3Jiftts0O5a/d13371zIVzeM?invite=cr-MSx2MkIsNzM1MDU0Myw

**Comment by OmerBenGera** [comment] 2023-11-03 13:48
How do I replicate the issue?

**Comment by OmerBenGera** [comment] 2023-11-24 17:28
Any news regarding this?

**Comment by Sckaletz** [comment] 2023-11-24 20:47
I've pretty much added all the information I'm able to give you in order to replicate the problem. But you can just close this, since lowering the amount og mobs in the chunk solves the issue.

**Comment by OmerBenGera** [comment] 2023-12-16 11:11
Check out latest dev build, let me know if it is better.
Old chunks that had too many entities will probably still crash the game, you need to find a way to kill them.

**Comment by OmerBenGera** [comment] 2024-01-12 14:17
Closing this as it seems to be fixed
If the issue continues let me know

**Closed by OmerBenGera** 2024-01-12 14:17 UTC
Labels: 🔧 Potential fix, ✔️ Confirmed
