### ISSUE TITLE
Issue with listen-paper-pre-spawn-event

### ISSUE THREAD

**Issue by WarnDangerous** [BG-Software-LLC/WildStacker#278] opened 2021-08-19 22:39 UTC
### Minecraft's Version

Airplane 1.16.5

### Plugin's Version

b185

### Describe the bug

When I use 
listen-paper-pre-spawn-event: true
with "upgradeablespawners", mobs are stacked correctly, but spawner add only 1 mob to the stack every time it spawns mobs, instead of 3-4 (as a vanilla spawner)

and if I set listen-paper-pre-spawn-event: false, then spawner spawn 3-4 different mobs.

### To Reproduce

Set listen-paper-pre-spawn-event: true and uses an upgradeablespawners, you'll see it only adds 1 mobs per 1 mobs to the stack, instead of 3-4.

### Additional Information

Upgradeablespawners' dev told me the issue wasn't on his side, and I'm using his latest spigot release (2.3.3)

**Comment by OmerBenGera** [comment] 2021-08-20 12:40
Duplicate of #275

**Comment by OmerBenGera** [comment] 2021-08-20 13:53
Fixed in latest dev build

**Closed by OmerBenGera** 2021-08-20 13:53 UTC
Labels: Confirmed
