### ISSUE TITLE
Compatibility issue with EcoBosses

### ISSUE THREAD

**Issue by Krumpli2** [BG-Software-LLC/WildStacker#717] opened 2023-01-02 20:22 UTC
### Minecraft's Version

git-Purpur-1632 (MC: 1.18.2)*

### Plugin's Version

2022.6-b407 - DEV

### Describe the bug

If WildStacker is in server and i kill the boss, then no kill message/kill reward. But if i unload, everything works
I tried disable world/mob, but nothing.. if i disable "entities" features, everything works.. But i need stacked entities

![image](https://user-images.githubusercontent.com/19935455/210275211-d68ea84a-8f07-4800-b7e7-d70bcb396c83.png)

### To Reproduce

Download and place WildStacker + eco + EcoBosses to the server
Restart the server and done.. You can spawn test mob with cmd: /ecobosses spawn

**Comment by OmerBenGera** [comment] 2023-01-05 19:14
EcoBosses should have custom spawn cause that you can filter the entities by that.
Add their custom spawn cause to the blacklist section - let me know if it helps.

**Comment by Krumpli2** [comment] 2023-01-05 19:36
Still...

![image](https://user-images.githubusercontent.com/19935455/210865359-22d78318-2f6d-4756-b429-192b29895d45.png)
![image](https://user-images.githubusercontent.com/19935455/210865409-97865f62-e101-419d-9f31-99c85826ceac.png)

**Comment by OmerBenGera** [comment] 2023-01-06 07:56
Do /ws inspect, then click one of your bosses and you'll see their spawn cause.
Then just put it in the blacklist without the "ILLUSIONER"

**Comment by Krumpli2** [comment] 2023-01-06 18:42
Still....
![image](https://user-images.githubusercontent.com/19935455/211077444-defb6c8b-2ac8-4cc2-9568-aa8e8397e986.png)
![image](https://user-images.githubusercontent.com/19935455/211077519-b90c4d3e-024a-49ab-987a-a389bce2a224.png)
![image](https://user-images.githubusercontent.com/19935455/211077573-a3137827-ba28-461f-96d6-b8509f56d5a0.png)

**Comment by Krumpli2** [comment] 2023-01-06 18:46
If i set to false this value:
![image](https://user-images.githubusercontent.com/19935455/211078242-fcdd4a7e-b05c-4e63-b685-cc08895192f8.png)

Works:
![image](https://user-images.githubusercontent.com/19935455/211078321-12f02937-17d2-48aa-b72c-b8e07baf5487.png)

**Comment by OmerBenGera** [comment] 2023-01-07 08:48
I will look into it more deeply and will respond here as soon as I have some news.

**Comment by OmerBenGera** [comment] 2023-03-10 18:17
Does it work with latest dev build? @Krumpli2

**Comment by Krumpli2** [comment] 2023-03-12 11:04
No, @OmerBenGera

**Comment by OmerBenGera** [comment] 2023-03-17 18:28
I am happy to tell you that I found what the issue is, and I contacted Splodgebox regarding this.
Hopefully we will be able to push an update that addresses the issue as soon as possible

**Comment by OmerBenGera** [comment] 2023-03-17 21:11
The issue is fixed in latest dev build of WildStacker.
You will need to wait for Eco to update as well, as they also fixed something on their end.

I am closing this for now, if it still does not work, let me know

**Closed by OmerBenGera** 2023-03-17 21:11 UTC
Labels: ✔️ Confirmed
