### ISSUE TITLE
Stacked spawner sometimes only spawning non-stacked mobs

### ISSUE THREAD

**Issue by marvjosh1** [BG-Software-LLC/WildStacker#451] opened 2022-02-09 22:46 UTC
### Minecraft's Version

Purpur 1.18.1 1538

### Plugin's Version

dev build 274

### Describe the bug

Sometimes the stacked spawners only spawns unstacked entities, istead of stacked mobs

### To Reproduce

Place down a stacked spawner, wait for a while. Occasionally, it will start only spawning singular mobs

### Additional Information

https://www.youtube.com/watch?v=CNJ3R90PS68

**Comment by Skizzles** [comment] 2022-02-12 13:56
@OmerBenGera I think this is more so that the spawner is only spawning X amount of mobs at a time based off stack size. If I place 8 stacked spawner down then I get a only one x8 spawn, if I place 1 spawner down I only get one x1 spawn.

**Comment by OmerBenGera** [comment] 2022-02-12 14:01
> @OmerBenGera I think this is more so that the spawner is only spawning X amount of mobs at a time based off stack size. If I place 8 stacked spawner down then I get a only one x8 spawn, if I place 1 spawner down I only get one x1 spawn.
> 
> Basically spawners are not spawning 4 mobs from the spawner.

Spawners will not spawn 4 mobs, similar to how vanilla works.
The spawner will **attempt** to spawn a maximum of 4 mobs. This means that it will choose 4 random locations, and will try to spawn a mob in these locations. If it managed to spawn at least 1 mob, it will reset the delay, which makes the spawner spawn between 1 and 4 entities. The chance of spawning 4 mobs is unlikely to occur.
A more detailed explanation of how the mechanism actually works and the difference between it and the vanilla one can be found here:
https://wiki.bg-software.com/wildstacker/overview/spawners-stacker/spawners-override

@marvjosh1 Is this what you were referring to? If so, this is not a bug.

**Comment by marvjosh1** [comment] 2022-02-12 21:55
This is not exactly what I meant. The issue is, that the spawner, similarly to a vanilla spawner, **always** seemed to spawn unstacked mobs, (basically x1 stack size), although being a x4 Wither Skeleton Spawner.
Which resulted in the total stack amount at the bottom of the grinder being very noticeably smaller, in comparison to times when it was working as intended.

**Comment by marvjosh1** [comment] 2022-02-12 22:31
Further evidence to clarify what I mean: https://youtu.be/Wl4HWa-ueQA
There already was 3 stacked wither skeletons down below, but as seen by hovering over each wither skeleton spawned, it always only spawns singular ones.

**Comment by OmerBenGera** [comment] 2022-02-17 21:53
Try it on a server with only WildStacker installed on your server.
Also, check using `/ws inspect` that the spawner's stack size and the spawned mobs are actually 5 and 1

**Comment by Skizzles** [comment] 2022-03-02 11:02
After further testing @OmerBenGera, I found that the stacked spawner will spawn the correct amounts ONLY the first time. After it ends up spawning 1 per spawner in the stack (10 spawners = 10 mobs) every single time after.

When disabling linked-entities for the spawners I found this resolves.

**Comment by OmerBenGera** [comment] 2022-03-02 17:51
> After further testing @OmerBenGera, I found that the stacked spawner will spawn the correct amounts ONLY the first time. After it ends up spawning 1 per spawner in the stack (10 spawners = 10 mobs) every single time after.
> 
> When disabling linked-entities for the spawners I found this resolves.

Might be an issue with linked entities then.
I will look into it :)

**Comment by OmerBenGera** [comment] 2022-09-16 14:12
@marvjosh1 A lot of recodes were made since this issue was opened
Does it still occur with latest versions of the plugin?
Let me know.

**Comment by OmerBenGera** [comment] 2022-09-23 07:36
@marvjosh1 Have you tried it?

**Comment by marvjosh1** [comment] 2022-09-23 08:42
Hello,
unfortunaly I retired from the Void team and don't work there anymore, so Skizzles would have to respond for me.
I have contacted him about it though so I think he should respond soon!

**Comment by Skizzles** [comment] 2022-09-24 10:45
> @marvjosh1 A lot of recodes were made since this issue was opened Does it still occur with latest versions of the plugin? Let me know.

Hello Omer, sorry for late response. I subscribed to this issue now.

Based off my testing there are some cases where players have experienced this. Its quite random when it occurs as after a restart the player didnt have the issue anymore.

**Comment by OmerBenGera** [comment] 2022-09-24 13:04
> > @marvjosh1 A lot of recodes were made since this issue was opened Does it still occur with latest versions of the plugin? Let me know.
> 
> Hello Omer, sorry for late response. I subscribed to this issue now.
> 
> Based off my testing there are some cases where players have experienced this. Its quite random when it occurs as after a restart the player didnt have the issue anymore.

Even using latest versions of the plugin?

**Comment by OmerBenGera** [comment] 2022-09-24 14:57
> same bug with lastest version.. sometimes spawner like 20x spawn only 1 mob and player have to re-place it to fix.
> 
> Its a very old bug.. since 1.16.5 for me

The entire spawners system was recoded, therefore it's not relevant.
Let me know how to replicate it on a server with only WS installed.

**Comment by OmerBenGera** [comment] 2022-09-24 16:26
@kedavlar @Skizzles Check out latest dev build, hopefully it fixes the issue.
I made it so once the spawner is spawning an entity, WildStacker makes sure the spawner is overridden and if not it overrides it again.

**Comment by Skizzles** [comment] 2022-09-25 06:05
> @kedavlar @Skizzles Check out latest dev build, hopefully it fixes the issue. I made it so once the spawner is spawning an entity, WildStacker makes sure the spawner is overridden and if not it overrides it again.

Tested this jar and still have this problem, some spawners just won't spawn above 1 per spawner in stack.

**Comment by OmerBenGera** [comment] 2022-09-25 06:42
> > @kedavlar @Skizzles Check out latest dev build, hopefully it fixes the issue. I made it so once the spawner is spawning an entity, WildStacker makes sure the spawner is overridden and if not it overrides it again.
> 
> Tested this jar and still have this problem, some spawners just won't spawn above 1 per spawner in stack.

Wdym by "wont spawn above 1 per spawner in stack"?

**Comment by Skizzles** [comment] 2022-09-25 07:11
> > > @kedavlar @Skizzles Check out latest dev build, hopefully it fixes the issue. I made it so once the spawner is spawning an entity, WildStacker makes sure the spawner is overridden and if not it overrides it again.
> > 
> > Tested this jar and still have this problem, some spawners just won't spawn above 1 per spawner in stack.
> 
> Wdym by "wont spawn above 1 per spawner in stack"?

5x spawner only ever spawns 5 mobs each time. It never spawns 2-4

**Comment by OmerBenGera** [comment] 2022-09-25 07:59
> > > > @kedavlar @Skizzles Check out latest dev build, hopefully it fixes the issue. I made it so once the spawner is spawning an entity, WildStacker makes sure the spawner is overridden and if not it overrides it again.
> > > 
> > > 
> > > Tested this jar and still have this problem, some spawners just won't spawn above 1 per spawner in stack.
> > 
> > 
> > Wdym by "wont spawn above 1 per spawner in stack"?
> 
> 5x spawner only ever spawns 5 mobs each time. It never spawns 6+

So we know that the spawner are infact overridden by the plugin, as it spawns 5 mobs.
Mind sharing with me with your config file?

**Comment by Skizzles** [comment] 2022-09-29 11:12
@OmerBenGera https://paste.skizzles.me/enigijatad.yaml

**Comment by OmerBenGera** [comment] 2022-10-10 07:54
> So, I report what the players told me.
> 
> The spawner bug occurs randomly only when there are no mobs already present, so the first time they spawn the mobs they only have 1x, the next time, however, it is fixed automatically and have the correct value based on the number of spawners . The problem is that the iron golems spawn and die right away, so they don't have time to join with others and it gets bugged until they take the spawner off and on again.

Mind taking a video of this?
Uoload it to an online streaming service and send me a link here

**Comment by Skizzles** [comment] 2022-10-20 21:30
https://screenshots.skizzles.me/wAnA3/CegIMUyO72.mp4

You can see here it's not working, but then 3 hrs later the player said it now is.

**Comment by OmerBenGera** [comment] 2022-10-21 06:47
Very weird.
I'll add a debug feature, so you can click a spawner to start debugging it, and hopefully we'll understand what causes this weird behavior to occur.

**Comment by OmerBenGera** [comment] 2022-10-21 07:54
I added the spawners debug in latest dev build.
When the issue occurs with a spawner, use `/ws debug` while looking at the spawner, and wait for it to spawn the bugged entity.
Then, run the command again while looking at the spawner to disable the debug mode for the spawner.
After that, you'll see in console a few messages - send them here via pastebin.

Don't enable it for multiple spawners at a time, otherwise we will not understand anything from the output.

**Comment by Skizzles** [comment] 2022-10-22 21:24
@OmerBenGera no output is shown in console when the command is run.

Do not see any output

**Comment by Skizzles** [comment] 2022-10-22 21:40
https://youtu.be/Q8LTT9CmNlQ

Video of the stacks being 2x and not 20x

**Comment by OmerBenGera** [comment] 2022-10-23 04:19
> @OmerBenGera no output is shown in console when the command is run.
> 
> Do not see any output

Interesting... something is overriding wildstacker spawners after all..

**Comment by Skizzles** [comment] 2022-10-24 08:41
> > @OmerBenGera no output is shown in console when the command is run.
> > Do not see any output
> 
> Interesting... something is overriding wildstacker spawners after all..

What is our next steps then? As I can get the same behavior with just wildstacker installed then I wonder what the problem is.

**Comment by Skizzles** [comment] 2022-10-27 06:28
> > > > @OmerBenGera no output is shown in console when the command is run.
> > > > Do not see any output
> > > 
> > > 
> > > Interesting... something is overriding wildstacker spawners after all..
> > 
> > 
> > What is our next steps then? As I can get the same behavior with just wildstacker installed then I wonder what the problem is.
> 
> For no reason something is overriding WS's spawners, or that WildStacker doesnt register them correctly. What is more weird is that it should do it when mobs spawn, however it doesnt... What spigot jar do you use (exacr output of /version) as well as the java version that is being used.

Current: git-Purpur-1758 (MC: 1.19.2)
Java 17

**Comment by OmerBenGera** [comment] 2022-10-28 11:12
@Skizzles Check out latest dev build and use the debug command again on a bugged spawner.
Let me know what is printed to console

**Comment by Skizzles** [comment] 2022-10-31 02:03
The debug command helped a lot, was able to see the spawner needed more room due to wither skeletons being 2.4 blocks.

Closing this as resolved, but that debug command should be kept!

**Closed by Skizzles** 2022-10-31 02:03 UTC
Labels: ❌ Unconfirmed
