### ISSUE TITLE
Spawners slowing down and not being counted as wildstacks.

### ISSUE THREAD

**Issue by Rockin21** [BG-Software-LLC/WildStacker#744] opened 2023-01-29 05:00 UTC
### Minecraft's Version

Pufferfish build 24 1.19

### Plugin's Version

2022.6.b407

### Describe the bug

Spawners slow down and do not detect nearby players. It takes 10 seconds to tick down 1 second. The best way of describing it is that they do not register under wildstacker anymore and take on vanilla traits.

When this happens they spawn regular mob amounts as if it were 1 singular spawner, e.g, a stack of 32 begins only spawning 1 mob. The only way make it work is breaking the spawner stack and re placing it down. This process must be repeated everytime a player leaves the location and comes back.

### To Reproduce

Place down a stack of spawners, unload the chunk/tp away, and return. 

### Additional Information

![image](https://user-images.githubusercontent.com/110613392/215305899-9a264ee3-8ea2-4dd8-b233-6c114e1e8ec1.png)

**Comment by OmerBenGera** [comment] 2023-02-03 08:48
Duplicate of #696

**Closed by OmerBenGera** 2023-02-03 08:48 UTC
Labels: Pending
