### ISSUE TITLE
Stacked spawners not spawning extra mobs

### ISSUE THREAD

**Issue by JasonHorkles** [BG-Software-LLC/WildStacker#233] opened 2021-07-18 05:38 UTC
### Minecraft's Version

Tuinity version git-Tuinity-21 (MC: 1.17.1)

### Plugin's Version

WildStacker version 3.6.0-DEVb161

### Describe the bug

When stacking spawners, the amount of spawned mobs appears to be as if there was only one spawner there. For example, I stacked 150+ spawners and yet only 3-4 mobs actually spawned.

### To Reproduce

Stack spawners

### Additional Information

Config: https://paste.gg/p/JasonHorkles/d6be28abf947447ebd618778592f0771

**Comment by OmerBenGera** [comment] 2021-07-18 14:37
Note to myself: only happens when entities are disabled.

**Comment by Billabomb75** [comment] 2021-07-20 18:38
Try disabling the Listen to Paper option in the Spawners Settings...

**Comment by JasonHorkles** [comment] 2021-07-20 20:01
Yep that fixes it!

**Comment by OmerBenGera** [comment] 2021-07-20 20:24
Another note: seems to get fixed when disabling Paper listening

**Comment by OmerBenGera** [comment] 2021-07-20 20:52
Duplicate of #226

**Closed by OmerBenGera** 2021-07-20 20:52 UTC
Labels: Bug Report, Further Investigation
