### ISSUE TITLE
Stacking / Clear entities bug

### ISSUE THREAD

**Issue by Rhys00** [BG-Software-LLC/WildStacker#572] opened 2022-08-03 22:35 UTC
### Minecraft's Version

1.8.8

### Plugin's Version

#327 03/08/2022 11:03:26

### Describe the bug

Mobs still stack when I use an egg. https://streamable.com/17aiza

This also goes for the same as the kill task too.

### To Reproduce

Put the mobtype and then egg like seen here https://prnt.sc/pvF89mNpl8QB and then spawn the mob in and you still see they stack. Here is a video of me doing it https://streamable.com/17aiza

**Comment by OmerBenGera** [comment] 2022-08-04 00:02
Try using `SPAWNER_EGG` instead of `EGG`, let me know if it works.

**Comment by Rhys00** [comment] 2022-08-04 00:09
> 

They still stack

**Comment by OmerBenGera** [comment] 2022-08-04 06:24
> > 
> 
> They still stack

Upload your entire config and send it here

**Comment by Rhys00** [comment] 2022-08-04 13:44
> > > 
> > 
> > 
> > They still stack
> 
> Upload your entire config and send it here

https://paste.helpch.at/kilozahaxo.bash

To note I use EliteBosses also so I need them not to stack and clear lag. Thats why I am trying to get this to work.

**Comment by OmerBenGera** [comment] 2022-08-04 17:50
As I told you, you need to use "SPAWNER_EGG" instead of "EGG" as a spawn cause filter.
Also, if you use EliteBosses, these mobs have a different spawn cause than vanilla. You can check it out and filter by it using the inspect tool - `/stacker inspect`

This is not a bug with the plugin, closing this.

**Closed by OmerBenGera** 2022-08-04 17:50 UTC
Labels: 📝 Missing information
