### ISSUE TITLE
Disabling item stacker causes overstacked items from other plugins to disappear

### ISSUE THREAD

**Issue by ArmonicPvP** [BG-Software-LLC/WildStacker#610] opened 2022-09-17 02:49 UTC
### Minecraft's Version

1.19.2

### Plugin's Version

3.8.1-b74

### Describe the bug

When an item from another plugin drops a giant stack of another item that is overstacked, that stack of items will become invisible and either default to 64 items or simply disappear

### To Reproduce

Disable item stacker and use a plugin that drops items to the ground in a giant stack (like mcMMO and tree feller or crates when your inventory is full or towny resources when your inventory is full)

**Comment by ArmonicPvP** [comment] 2022-09-17 03:23
This issue also happened when I had looting 255 + sharpness 255 + sweeping edge 255 on a sword and killed 100 pigmen, all of their items disappeared and I only got 1 stack of each as invisible items

**Comment by OmerBenGera** [comment] 2022-09-17 09:48
This is not a bug of WildStacker.
Even without WildStacker, when dropping an item with a large stack size, it will not be visually seen by the client.
Your plugin that drops the items should make sure the maximum item amount of the item is ItemStack#getMaxStackSize.
The plugin can hook directly into WildStacker and use its methods to drop items without a limit, and let WildStacker handle the drops.

**Comment by OmerBenGera** [comment] 2022-09-23 07:38
I am closing this as it doesn't seem like an issue with WildStacker.

**Closed by OmerBenGera** 2022-09-23 07:38 UTC
Labels: ❌ Unconfirmed
