### ISSUE TITLE
Sculk Catalyst does not generate Sculk

### ISSUE THREAD

**Issue by OreoKirby** [BG-Software-LLC/WildStacker#586] opened 2022-08-18 01:41 UTC
### Minecraft's Version

1.19.2 Paper 131

### Plugin's Version

WildStacker-3.8.1-b337

### Describe the bug

Sculk blocks do not generate when a mob dies within 8 blocks of a Sculk Catalyst.

### To Reproduce

1. Start up a server running the latest release of Paper-Spigot without WIldStacker installed.
2. Place a Sculk Catalyst in the ground surrounded by Stone. 
3. Spawn a Spider and kill it within an 8 block radius of the Sculk Catalyst.
4. Watch XP orbs drop onto the ground.
5. The Stone surrounding the Sculk Catalyst WILL turn to Sculk and Sculk Veins.

6. Start up a server running the latest release of Paper-Spigot with WildStacker installed and loaded.
7. Place a Sculk Catalyst in the ground surrounded by Stone. 
8. Spawn a Spider and kill it within an 8 block radius of the Sculk Catalyst.
9. Watch XP orbs drop onto the ground.
10. The Stone surrounding the Sculk Catalyst will NOT turn to Sculk and Sculk Veins.

### Additional Information

This bug does not effect Sculk spreading when a player is killed.

This bug is only present on Paper 131 when WildStacker is loaded.

Possibly related to fb46a1b7372ae5648b9d2ae180785037390469b2?

**Comment by Skizzles** [comment] 2022-08-19 04:17
@OreoKirby Could you provide your "entities" section of your Stacker config, I believe I was able to locate the cause.

@OmerBenGera for reference, I added "whitelist" values to make only spawner mobs stack for me and this same issue occurred.

**Comment by OreoKirby** [comment] 2022-08-19 04:48
# Here you can configurable all features related to stacked entities.
entities:
  # Should entities get stacked on the server?
  enabled: true

  # How many blocks from the entity should be checked for other entities to stack into?
  # EntityType list: https://bg-software.com/entities/
  # SpawnReason list: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html
  # You can combine both filters using "ENTITY_TYPE:SPAWN_REASON"
  merge-radius:
    all: 10
    CHICKEN:BREEDING: 15
    COW:BREEDING: 15
    PIG:BREEDING: 15
    SHEEP:BREEDING: 15

  # Custom display-name for the entities.
  # If you don't want a display-name, use "custom-name: ''"
  # {0} represents stack amount
  # {1} represents entity type
  # {2} represents entity type in upper case
  # {3} represents the upgrade's display name
  custom-name: '&6x{0} &f&o{1}'

  # Blacklisted entities are entities that won't get stacked.
  # EntityType list: https://bg-software.com/entities/
  # SpawnReason list: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html
  # You can combine both filters using "ENTITY_TYPE:SPAWN_REASON"
  # If you wish to disable blacklisted entities, use "blacklist: []"
  blacklist:
  - ALLAY
  - BEE
  - COD
  - ENDERMAN
  - GUARDIAN
  - PILLAGER
  - PUFFERFISH
  - SALMON
  - TROPICAL_FISH
  - VILLAGER
  - WARDEN
  - WOLF
  - ZOMBIE_VILLAGER
  - ZOMBIFIED_PIGLIN

  # Whitelisted entities are entities that will get stacked.
  # EntityType list: https://bg-software.com/entities/
  # SpawnReason list: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html
  # You can combine both filters using "ENTITY_TYPE:SPAWN_REASON"
  # If you wish to disable whitelisted entities, use "whitelist: []"
  whitelist: []

  # Set a maximum stack for specific entities.
  # Make sure you follow the "ENTITY-TYPE" format.
  # You can use 'all' as a global limit (all: 20 will set all entities to be limited to 20 per stack)
  # If you don't want any limits, you can set a random type.
  limits:
    all: 50

  # Set a minimum required entities to stack for specific entities.
  # Make sure you follow the "ENTITY-TYPE" format.
  # You can use 'all' as a global limit (all: 20 will set all entities to must have at least 20 entities around before stacking)
  # If you don't want any limits, you can set a random type.
  minimum-required:
    all: 6
    BLAZE:SPAWNER: 5
    CAVE_SPIDER:SPAWNER: 5
    MAGMA_CUBE:SPAWNER: 5
    SILVERFISH:SPAWNER: 5
    SPIDER:SPAWNER: 5
    SKELETON:SPAWNER: 5
    ZOMBIE:SPAWNER: 5
    CHICKEN:EGG: 2
    CHICKEN:BREEDING: 5
    COW:BREEDING: 5
    PIG:BREEDING: 5
    SHEEP:BREEDING: 5

  # A list of worlds entities won't get stacked inside them (case-sensitive)
  disabled-worlds:
  - world_void

  # Set a maximum amount of entity objects in a chunk.
  # If you want to disable the feature, set it to 0.
  chunk-limit: 0

  # Should particles be spawned when an entity gets stacked?
  # If you want to edit the particles, check the particles file.
  particles: false

  # A list of WorldGuard regions entities won't get stacked inside them (case-sensitive)
  disabled-regions: []

  # Blacklisted names is a list of names that when an entity has this name, it won't get stacked.
  # Color codes are supported, as well as regex.
  # If you wish to enable stacking of all entities based on their name, use "name-blacklist: []"
  name-blacklist: []

  # How much time should be passed between auto-stacking? (in ticks)
  # If you wish to disable the auto-stacking task, set the stack-interval to 0.
  stack-interval: 200

  # A list of all checks that the plugin does before trying to stack two entities together.
  stack-checks:
    AGE: true
    ANIMAL_OWNER: true
    AXOLOTL_TYPE: true
    AXOLOTL_PLAYING_DEAD: false
    BAT_AWAKE: false
    CAN_BREED: true
    CAT_COLLAR_COLOR: true
    CAT_TYPE: true
    CREEPER_CHARGED: true
    ENDERMAN_CARRIED_BLOCK: true
    EXACT_AGE: false
    FROG_TOUNGE_TARGET: false
    FROG_TYPE: true
    GLOW_SQUID_DARK_TICKS: false
    GOAT_SCREAMING: true
    GUARDIAN_ELDER: true
    HORSE_CARRYING_CHEST: true
    HORSE_COLOR: true
    HORSE_JUMP: true
    HORSE_MAX_TAME_PROGRESS: true
    HORSE_STYLE: true
    HORSE_TAME_PROGRESS: true
    HORSE_TYPE: true
    IS_IN_LOVE: true
    IS_TAMED: true
    LLAMA_COLOR: true
    LLAMA_STRENGTH: true
    MOOSHROOM_TYPE: true
    NAME_TAG: true
    NERFED: true
    OCELOT_TYPE: true
    PARROT_TYPE: true
    PHANTOM_SIZE: true
    PIG_SADDLE: true
    PUFFERFISH_STATE: true
    RABBIT_TYPE: true
    SHEEP_COLOR: true
    SHEEP_SHEARED: true
    SKELETON_TYPE: true
    SLIME_SIZE: true
    SPAWN_REASON: false
    TROPICALFISH_BODY_COLOR: true
    TROPICALFISH_TYPE: true
    TROPICALFISH_TYPE_COLOR: true
    UPGRADE: true
    VILLAGER_PROFESSION: true
    WOLF_ANGRY: true
    WOLF_COLLAR_COLOR: true
    ZOMBIE_BABY: true
    ZOMBIE_PIGMAN_ANGRY: false

  # A list of all actions that the plugin check before unstacking an entity stack.
  stack-split:
    BEE_AGRO: true
    ENTITY_BREED: true
    ENTER_VEHICLE: true
    IRON_GOLEM_AGRO: true
    MUSHROOM_SHEAR: true
    NAME_TAG: true
    PIGMAN_AGRO: true
    SHEEP_DYE: true
    SHEEP_SHEAR: true
    VILLAGER_INFECTION: true
    WOLF_AGRO: true

  # Linked-entities are entities that are linked to one spawner or more.
  # A spawner that has an entity linked to, will try to stack it's entities first to the linked one.
  # Linked entities feature won't work if entities-stacking is disabled.
  linked-entities:
    # Should entities be linked to spawners?
    enabled: true

    # The maximum distance that the linked entity can be from the spawner.
    # If the entity is too far, it will get unlinked automatically from the spawner.
    max-distance: 10

  # Instant-kill will kill the entire stack instead of unstack it by one.
  # When an entire stack dies, their drops are getting multiplied.
  # EntityType list: https://bg-software.com/entities/
  # DamageCause list:  https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/entity/EntityDamageEvent.DamageCause.html
  # You can combine both filters using "ENTITY_TYPE:DAMAGE_CAUSE" or "ENTITY_TYPE:SPAWN_REASON"
  # If you don't want instant-kill, use "instant-kill: []"
  instant-kill:
  - FALL
  - VOID

  # Nerfed entities are entities that cannot attack / target other entities and players.
  # EntityType list: https://bg-software.com/entities/
  # SpawnReason list: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html
  # You can combine filters using "ENTITY_TYPE:SPAWN_REASON"
  nerfed-entities:
    # A list of entities that will be nerfed.
    # If you want all entities to be nerfed, set this to [].
    whitelist:
    - EXAMPLE_MOB
    # A list of entities that won't be nerfed.
    blacklist: []
    # A list of worlds that entities can be nerfed in.
    # If you want entities to be nerfed inside all worlds, set this to [].
    worlds: []
    # Should nerfed entities be able to teleport?
    teleport: false

  # Stack-down is a feature that will force entities to stack to other entities that are below their y level.
  # This feature is great for flying entities, like blazes and ghasts.
  stack-down:
    # Should the stack-down feature be enabled on the server?
    enabled: true
    # A list of entities that will be forced to only stack down.
    # You can combine filters using "ENTITY_TYPE:SPAWN_REASON"
    stack-down-types:
    - BLAZE
    - GHAST

  # If a stacked entity dies from fire, should the fire continue to the next entity?
  keep-fire: false

  # If enabled, the placeholder '{}' will be replaced with the stack amount for mythic mobs.
  mythic-mobs-custom-name: true

  # A list of entities that should keep the lowest health when stacking.
  # EntityType list: https://bg-software.com/entities/
  # SpawnReason list: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html
  # You can combine filters using "ENTITY_TYPE:SPAWN_REASON"
  keep-lowest-health: []

  # When enabled, parents of the entity will get stacked together after breeding.
  stack-after-breed: false

  # When smart-breed is enabled, players will be consumed with two items in order to breed a stack.
  # No breeding animation will be played, and a new baby stack will be spawned with the correct amount.
  # This can prevent massive splits of the stack for breeding, and can help with performance.
  smart-breeding:
    enabled: false
    # When enabled, items for breeding will be consumed from the entire inventory instead of only hand.
    consume-entire-inventory: false

  # When enabled, entities' names will be shown only if player looks exactly towards them.
  hide-names: true

  # Should players be able to disable entity names for themselves?
  # In order to work, ProtocolLib should be installed.
  names-toggle:
    # Can entity names be toggled?
    enabled: false

    # What the toggle command will be?
    command: stacker names entity

  # Should entities can be killed fast by players (No damage-cooldown)?
  fast-kill: false

  # The default amount entities should get unstacked by.
  # Use the "ENTITY_TYPE:AMOUNT" or "ENTITY_TYPE:SPAWN_CAUSE:AMOUNT"
  default-unstack:
    all: 1

  # Should exp get added directly to killer instead of dropped to ground?
  # EntityType list: https://bg-software.com/entities/
  # SpawnReason list: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html
  # You can combine both filters using "ENTITY_TYPE:SPAWN_REASON"
  auto-exp-pickup: []

  # Set a custom exp sound when auto-exp-pickup is enabled.
  # You can set this to '' if you want to disable it.
  exp-pickup-sound: ENTITY_EXPERIENCE_ORB_PICKUP

  # Should eggs that are laid by stacked chickens be multiplied by it's stack size?
  egg-lay-multiply: false

  # Should scout that are dropped by grown turtles by multiplied by it's stack size?
  scute-multiply: false

  # Should vanilla equipment of entities get cleared after they unstack?
  clear-equipment: false

  # Should corpses be spawned when entity dies ("death animations")?
  spawn-corpses: true

  # When enabled, entities will be one shot by specific tools.
  one-shot:
    # Should this feature be enabled?
    enabled: false
    # A list of tools that can one shot entities.
    tools:
    - DIAMOND_SWORD
    - DIAMOND_AXE
    # A list of entities that will be one shot.
    # EntityType list: https://bg-software.com/entities/
    # SpawnReason list: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html
    # You can combine both filters using "ENTITY_TYPE:SPAWN_REASON"
    whitelist:
    - ALL

  # Should entities get stored into the database?
  store-entities: true

  # Should WildStacker add a custom entities-stacking setting to SuperiorSkyblock?
  # When enabling, make sure you add "entities_stacking" section to the settings menu.
  superiorskyblock-hook: false

  # Should drops get calculated in relation to the amount of mobs that died?
  multiply-drops: true

  # Should exp get calculated in relation to the amount of mobs that died?
  multiply-exp: true

  # Should damage be spread to the next stack?
  # If you deal more damage than the health of the entity, the rest of the damage will be dealt to the next stack.
  spread-damage: true

  # Which transform types should WildStacker listen to?
  # When an entity is transforming into another entity with one of the following reasons,
  # the plugin will convert it's data to the new entity.
  # A list of transform reasons can be find here:
  # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityTransformEvent.TransformReason.html
  filtered-transforms:
  - PIGLIN_ZOMBIFIED

  # Should entities fill vehicles entirely by stacked entities?
  # When enabled, vehicles will be able to get filled with two entities.
  # This can cause players to not be able to enter these vehicles.
  entities-fill-vehicles: true

**Comment by OmerBenGera** [comment] 2022-08-19 07:35
Fixed in latest dev build

**Closed by OmerBenGera** 2022-08-19 07:35 UTC
Labels: ✔️ Confirmed
