### ISSUE TITLE
Could not pass event BlockPlaceEvent to WildStacker v2022.6-b405

### ISSUE THREAD

**Issue by JoeDalton9027** [BG-Software-LLC/WildStacker#706] opened 2022-12-23 12:05 UTC
### Minecraft's Version

Spigot 1.19.3

### Plugin's Version

WildStacker v2022.6-b405

### When placing spawner block of 1.19.3 i got this error on console

[13:02:08] [Server thread/WARN]: Skipping Entity with id 
[13:02:08] [Server thread/ERROR]: Could not pass event BlockPlaceEvent to WildStacker v2022.6-b405
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.MobSpawnerData.a()" because "net.minecraft.world.level.block.entity.TileEntityMobSpawner.d().f" is null
	at org.bukkit.craftbukkit.v1_19_R2.block.CraftCreatureSpawner.getSpawnedType(CraftCreatureSpawner.java:18) ~[paper-1.19.3.jar:git-Paper-323]
	at com.bgsoftware.wildstacker.objects.WStackedSpawner.<init>(WStackedSpawner.java:54) ~[WildStacker-2022.6-b405.jar:?]
	at com.bgsoftware.wildstacker.objects.WStackedSpawner.<init>(WStackedSpawner.java:47) ~[WildStacker-2022.6-b405.jar:?]
	at com.bgsoftware.wildstacker.handlers.SystemHandler.getStackedSpawner(SystemHandler.java:252) ~[WildStacker-2022.6-b405.jar:?]
	at com.bgsoftware.wildstacker.handlers.SystemHandler.getStackedSpawner(SystemHandler.java:241) ~[WildStacker-2022.6-b405.jar:?]
	at com.bgsoftware.wildstacker.objects.WStackedSpawner.of(WStackedSpawner.java:64) ~[WildStacker-2022.6-b405.jar:?]
	at com.bgsoftware.wildstacker.objects.WStackedSpawner.of(WStackedSpawner.java:59) ~[WildStacker-2022.6-b405.jar:?]
	at com.bgsoftware.wildstacker.listeners.SpawnersListener.onBlockPlace(SpawnersListener.java:150) ~[WildStacker-2022.6-b405.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor466.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-323]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:396) ~[paper-1.19.3.jar:git-Paper-323]
	at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:403) ~[paper-1.19.3.jar:git-Paper-323]
	at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:587) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1963) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-323]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-323]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-323]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-323]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-323]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.3.jar:git-Paper-323]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.3.jar:git-Paper-323]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-323]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

### To Reproduce

This happends when i place the new 1.19.3 spawner block
nothing more

**Comment by OmerBenGera** [comment] 2022-12-23 14:07
Duplicate of #705

**Comment by JoeDalton9027** [comment] 2022-12-23 14:36
This is not a duplicate because version is not the same 

I used the last Dev build 405 
And #705  is using devbuild 404

**Comment by OmerBenGera** [comment] 2022-12-23 16:06
Update your spigot version, hopefully will be fixed
This is not an issue with the plugin - the plugin calls Bukkit methods that throw this error.

**Comment by JoeDalton9027** [comment] 2022-12-24 10:18
Hello, updated to paper Build 354 and the issue is fixed.
Thank you ! 

Merry christmas to you

**Comment by OmerBenGera** [comment] 2022-12-24 10:31
> Hello, updated to paper Build 354 and the issue is fixed. Thank you !
> 
> Merry christmas to you

You too, glad it is fixed :)

**Closed by OmerBenGera** 2022-12-24 10:31 UTC
Labels: ❌ Unconfirmed
