### ISSUE TITLE
Error spam #2

### ISSUE THREAD

**Issue by Faceless0102** [BG-Software-LLC/WildStacker#141] opened 2021-04-06 08:48 UTC
**Minecraft's Version**
PaperSpigot 1.12.2

**Plugin's Version**: -
b106

**Describe the bug**
https://pastebin.com/BmE2VGXp

**Comment by ElBananaa** [comment] 2021-04-07 00:24
Was already reported in #139 and #104

**Comment by OmerBenGera** [comment] 2021-04-10 05:55
Duplicate of #104

**Closed by OmerBenGera** 2021-04-10 05:55 UTC
Labels: Bug Report, Pending
