### ISSUE TITLE
WildStacker does not properly work with my plugin

### ISSUE THREAD

**Issue by ProtousSLO** [BG-Software-LLC/WildStacker#530] opened 2022-06-28 10:12 UTC
### Minecraft's Version

1.17.1+
purpur

### Plugin's Version

Latest

### Describe the bug

My plugin drops Heads of the animal you kill, whenever you kill an animal with stack size of x2 or greater, It will drop 2 heads. Whenever there is only a single animal or x1 stack size It will drop 1 head. I want it to only drop 1 head and not 2. And whenever the whole stack dies at once, be with lava or fall damage, It will only drop 1 head even If there is a stack of 10, It will drop a single head.

### To Reproduce

... own the plugin

### Additional Information

I am not the plugin developer however the developer seems to think It is something with WildStacker.

**Comment by OmerBenGera** [comment] 2022-06-28 16:55
WildStacker automatically multiplies the drops you add to EntityDeathEvent. It doesnt make sense to drop one head from multiple entites, thats the point of having them stacked.

Anyways not a bug, closing this.
A solution is to drop the items manually.

**Closed by OmerBenGera** 2022-06-28 16:55 UTC
Labels: Pending

**Comment by ProtousSLO** [comment] 2022-06-28 17:17
![image](https://user-images.githubusercontent.com/108335578/176243534-35869098-afb2-4d4b-a64f-c5b033f3e41a.png)

**Comment by ProtousSLO** [comment] 2022-06-28 18:44
That's not me, that's the developer.

**Comment by OmerBenGera** [comment] 2022-06-28 18:55
> That's not me, that's the developer.

Then he should be here and talk with me directly.
You shouldnt send messages between us back and forth

**Comment by ProtousSLO** [comment] 2022-06-28 18:59
It is what It is, seems that's the only way I can fix this.

**Comment by ProtousSLO** [comment] 2022-06-28 20:08
![image](https://user-images.githubusercontent.com/108335578/176275408-32091e29-7c17-441d-8769-8792aee27e18.png)

**Comment by OmerBenGera** [comment] 2022-06-28 20:31
> ![image](https://user-images.githubusercontent.com/108335578/176275408-32091e29-7c17-441d-8769-8792aee27e18.png)

Ask him to debug whether the event is called more than once or not
