### ISSUE TITLE
villagers cannot breeding

### ISSUE THREAD

**Issue by amarcais53** [BG-Software-LLC/WildStacker#199] opened 2021-06-15 17:19 UTC
**Minecraft's Version**
[19:09:11 INFO]: Checking version, please wait...
[19:09:12 INFO]: This server is running Purpur version git-Purpur-1156 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 13 version(s) behind
Previous version: git-Purpur-1169 (MC: 1.16.5)

IM ON JAVA 16

**Plugin's Version**: -
b-137

**Describe the bug**
for some reason when i enable item stacking villagers are not able to breed with other one but if i remove the plugin they can do it again and i have another issue ### **idk if its related but when they destroy carrots on the ground they do not replant them**

**To Reproduce**
setup a farm like on the video and drop carrots to villagers (drop more than 18 stack if they take more than 18 stack its buged because the villager inventory is only 9 stack )
ON this video we can see at the begining villager with carrots on inv because they was here before i instaled wildstacker and then when i instal wildstacker and kill them they cant take carrots anymore
im using shopkeeper to see the inventory of villager

**Additional information**
nothing check the video
https://www.youtube.com/watch?v=iAZ6ZW6mVWQ

**Comment by amarcais53** [comment] 2021-06-15 18:16
its confirmed when block stacking is here villagers cannot replant carrots and when i remove they can

**Comment by amarcais53** [comment] 2021-06-15 18:22
oh i was a litlle bite behind on builds sorry now they replant but the bug for breeding is still here

**Comment by OmerBenGera** [comment] 2021-06-18 10:27
Duplicate of #181

**Closed by OmerBenGera** 2021-06-18 10:27 UTC
Labels: Bug Report, Pending
