### ISSUE TITLE
Could not pass event EntityDamageByBlockEvent to WildStacker v2024.4

### ISSUE THREAD

**Issue by smscentras** [BG-Software-LLC/WildStacker#997] opened 2024-12-27 09:26 UTC
### Minecraft's Version

Purpur 1.21.1

### Plugin's Version

WildStacker v2024.4

### Describe the bug

`[09:34:57] [Server thread/ERROR]: Could not pass event EntityDamageByBlockEvent to WildStacker v2024.4
java.lang.ClassCastException: class org.bukkit.event.HandlerList cannot be cast to class com.bgsoftware.wildstacker.utils.events.BiHandlerList (org.bukkit.event.HandlerList is in unnamed module of loader java.net.URLClassLoader @5762806e; com.bgsoftware.wildstacker.utils.events.BiHandlerList is in unnamed module of loader 'WildStacker-2024.4.jar' @6762f9fa)
	at WildStacker-2024.4.jar/com.bgsoftware.wildstacker.listeners.EntitiesListener.recallDamageEvent(EntitiesListener.java:215) ~[WildStacker-2024.4.jar:?]
	at WildStacker-2024.4.jar/com.bgsoftware.wildstacker.listeners.EntitiesListener.handleEntityDamage(EntitiesListener.java:229) ~[WildStacker-2024.4.jar:?]
	at WildStacker-2024.4.jar/com.bgsoftware.wildstacker.listeners.EntitiesListener.handleEntityDamage(EntitiesListener.java:211) ~[WildStacker-2024.4.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor85.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-2329-803bf62]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callEvent(CraftEventFactory.java:277) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1219) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1214) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at org.bukkit.craftbukkit.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1158) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at org.bukkit.craftbukkit.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1101) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at org.bukkit.craftbukkit.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1257) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.entity.LivingEntity.handleEntityDamage(LivingEntity.java:2420) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1553) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.entity.monster.Guardian.hurt(Guardian.java:362) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.level.block.CampfireBlock.entityInside(CampfireBlock.java:109) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.entityInside(BlockBehaviour.java:1230) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.entity.Entity.checkInsideBlocks(Entity.java:1712) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.entity.Entity.tryCheckInsideBlocks(Entity.java:1371) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.entity.Entity.move(Entity.java:1307) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.entity.LivingEntity.handleRelativeFrictionAndCalculateMovement(LivingEntity.java:3159) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.entity.LivingEntity.travel(LivingEntity.java:3093) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.entity.monster.Guardian.travel(Guardian.java:381) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3619) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.entity.Mob.aiStep(Mob.java:708) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.entity.monster.Monster.aiStep(Monster.java:44) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.entity.monster.Guardian.aiStep(Guardian.java:311) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3267) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.entity.Mob.tick(Mob.java:469) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1330) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:761) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:738) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1851) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:513) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1642) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1342) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.1.jar:1.21.1-2329-803bf62]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]`

### To Reproduce

Start server

**Comment by OmerBenGera** [comment] 2024-12-27 09:36
Duplicate of #993

**Closed by OmerBenGera** 2024-12-27 09:36 UTC
Labels: Pending
