### ISSUE TITLE
Could not pass event CreatureSpawnEvent to WildStacker 

### ISSUE THREAD

**Issue by LynxError** [BG-Software-LLC/WildStacker#145] opened 2021-04-09 19:31 UTC
**Minecraft's Version**
paper-1.16.5-584.jar

**Plugin's Version**: -
install 3.5.1 and higher did not install less then 

**Describe the bug**
[14:13:53] [Server thread/ERROR]: Could not pass event CreatureSpawnEvent to WildStacker v3.5.1-DEVb103
all ver
https://pastebin.com/HuxSJS33

[14:13:53] [Server thread/ERROR]: Could not pass event CreatureSpawnEvent to WildStacker v3.5.1-DEVb103
java.lang.NullPointerException: null
	at com.bgsoftware.wildstacker.listeners.EntitiesListener.lambda$onEntitySpawnLow$7(EntitiesListener.java:520) ~[?:?]
	at com.bgsoftware.wildstacker.listeners.EntitiesListener$$Lambda$7014/0x000000003530b340.accept(Unknown Source) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
	at com.bgsoftware.wildstacker.listeners.EntitiesListener.onEntitySpawnLow(EntitiesListener.java:518) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor525.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-584]
	at org.bukkit.plugin.EventExecutor$$Lambda$4575/000000000000000000.execute(Unknown Source) ~[?:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-584]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-584]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-584]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:701) ~[patched_1.16.5.jar:git-Paper-584]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:622) ~[patched_1.16.5.jar:git-Paper-584]
	at net.minecraft.server.v1_16_R3.WorldServer.addEntity0(WorldServer.java:1302) ~[patched_1.16.5.jar:git-Paper-584]
	at net.minecraft.server.v1_16_R3.WorldServer.addEntity(WorldServer.java:1203) ~[patched_1.16.5.jar:git-Paper-584]
	at net.minecraft.server.v1_16_R3.EntitySlime.die(EntitySlime.java:263) ~[patched_1.16.5.jar:git-Paper-584]
	at net.minecraft.server.v1_16_R3.EntityLiving.cU(EntityLiving.java:561) ~[patched_1.16.5.jar:git-Paper-584]
	at net.minecraft.server.v1_16_R3.EntityLiving.entityBaseTick(EntityLiving.java:436) ~[patched_1.16.5.jar:git-Paper-584]
	at net.minecraft.server.v1_16_R3.EntityInsentient.entityBaseTick(EntityInsentient.java:315) ~[patched_1.16.5.jar:git-Paper-584]
	at net.minecraft.server.v1_16_R3.Entity.tick(Entity.java:498) ~[patched_1.16.5.jar:git-Paper-584]
	at net.minecraft.server.v1_16_R3.EntityLiving.tick(EntityLiving.java:2543) ~[patched_1.16.5.jar:git-Paper-584]
	at net.minecraft.server.v1_16_R3.EntityInsentient.tick(EntityInsentient.java:378) ~[patched_1.16.5.jar:git-Paper-584]
	at net.minecraft.server.v1_16_R3.EntitySlime.tick(EntitySlime.java:156) ~[patched_1.16.5.jar:git-Paper-584]
	at net.minecraft.server.v1_16_R3.WorldServer.entityJoinedWorld(WorldServer.java:960) ~[patched_1.16.5.jar:git-Paper-584]
	at net.minecraft.server.v1_16_R3.WorldServer$$Lambda$5537/000000000000000000.accept(Unknown Source) ~[?:?]
	at net.minecraft.server.v1_16_R3.World.a(World.java:946) ~[patched_1.16.5.jar:git-Paper-584]
	at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:646) ~[patched_1.16.5.jar:git-Paper-584]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1476) ~[patched_1.16.5.jar:git-Paper-584]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.16.5.jar:git-Paper-584]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1328) ~[patched_1.16.5.jar:git-Paper-584]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1116) ~[patched_1.16.5.jar:git-Paper-584]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-584]
	at net.minecraft.server.v1_16_R3.MinecraftServer$$Lambda$3129/000000000000000000.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Thread.java:836) [?:?]

**Comment by OmerBenGera** [comment] 2021-04-10 05:55
Duplicate of #104

**Closed by OmerBenGera** 2021-04-10 05:55 UTC
Labels: Bug Report, Pending
