### ISSUE TITLE
Villager will die when zombie attack

### ISSUE THREAD

**Issue by DarrienNN** [BG-Software-LLC/WildStacker#244] opened 2021-07-26 00:37 UTC
### Minecraft's Version

[Mon, 26. Jul 2021 08:34:20 SGT INFO] This server is running Paper version git-Paper-127 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 9a0263e)
You are 5 version(s) behind

### Plugin's Version

WildStacker - 170

### Describe the bug

Villager will get kill but not become zombie villager

When mobstack on villager will die if zombie attack

If mobstack off villager will become zombie villager if zombie attack and will not die

### To Reproduce

https://youtu.be/jj4zkI0pJR0

**Comment by OmerBenGera** [comment] 2021-07-28 20:59
Duplicate of #232

**Closed by OmerBenGera** 2021-07-28 20:59 UTC
Labels: Bug Report, Pending
