### ISSUE TITLE
EntityDamageEvent error spamming console

### ISSUE THREAD

**Issue by Nekosity12** [BG-Software-LLC/WildStacker#457] opened 2022-02-13 20:30 UTC
### Minecraft's Version

Purpur 1.18.1

### Plugin's Version

3.6.3 b283

### Describe the bug

This:
"Could not pass event EntityDamageEvent to WildStacker v3.6.3.283"
Keeps spamming our console. After searching around for the cause, we found out that it seems to be caused by endermen, more specifically we think it's caused by entitycramming, and not necessarily anything to do with specifically endermen.

### To Reproduce

Get a ton of endermen in a 1x1 area with no way to escape.
Just simply be near them as they entitycram
Check console for errors

### Additional Information

https://youtu.be/pCqr9R9qbEw
Video evidence

**Comment by brasilcraft54** [comment] 2022-02-16 11:32
It happens to me, too.  https://prnt.sc/26wijya

**Comment by OmerBenGera** [comment] 2022-02-16 18:39
Duplicate of #460

**Closed by OmerBenGera** 2022-02-16 18:39 UTC
Labels: Pending
