### ISSUE TITLE
Mob stacking with spawners not working perfectly well.

### ISSUE THREAD

**Issue by Ancienty** [BG-Software-LLC/WildStacker#777] opened 2023-04-04 23:48 UTC
### Minecraft's Version

1.8.9 Paper

### Plugin's Version

(2023.1-b427)

### Describe the bug

I don't really know if this counts as a bug but here I am.

So I'm using both WildStackers and EpicSpawners at the same time, and when a Spawner spawns a mob, they just spawn stacked as (the stack amount of the spawner) + 1

What I'm trying to say is:
If I place 5x Villager spawners, 6 villagers get spawned, if I place 4x Villager spawners, 5 villagers get spawned, if I place 10, then 11 spawns, so players just split their spawners and place them all one by one and each of those spawners spawn 2 mobs instead of 1, therefore it works as if they have double the amount of the spawners they actually have.

Let me know if there's something you couldn't understand, I'll do my best to rephrase.

### To Reproduce

I actually kinda mentioned this on the describe the bug part.

**Comment by OmerBenGera** [comment] 2023-04-05 09:43
Choose which plugin you want to handle spawners.
If you want WildStacker, get rid of EpicSpawners. If you want EpicSpawners, disable completely the spawners of WildStacker by setting `spawners.enabled` to false. Then if it still occurs, report it over EpicSpawners.

In both cases this is not an issue with WildStacker, so I am closing this.

**Closed by OmerBenGera** 2023-04-05 09:43 UTC
Labels: Pending

**Comment by OmerBenGera** [comment] 2023-04-05 13:15
> I'm asking this just to make sure:
> 
> WildStacker's spawner options are disabled, the problem still occurs. And this problem doesn't happen with "UltimateStacker" plugin, but that plugin is shit, that's why I'm using wildstacker.
> 
> Since it doesn't happen with the other plugin, I kinda thought this could be caused by WildStacker, are you certain that it's epic spawners related?

The issue is that both plugins handle spawners, and they don't work together.
Because you use EpicSpawners, I'd assume you use it for spawners, and therefore you must disable WildStacker spawners.
