### ISSUE TITLE
WildStacker does not work well with Insights

### ISSUE THREAD

**Issue by Sorusss** [BG-Software-LLC/WildStacker#533] opened 2022-07-04 09:12 UTC
### Minecraft's Version

Spigot 1.18.2

### Plugin's Version

WildStacker-3.8.0.jar

### Describe the bug

Hello, I have this problem that bothers me and I was told that it comes from WildStacker, I use Insights Plugin (to limit spawner) and when I put a spawner, it increases me by 1 but it does not go down when I break it, the Insights dev told me that in the past you made a version thats fixes this problem.

### To Reproduce

place and broke spawner to see

### Additional Information

https://gyazo.com/610f9380e58d1a3a2bacbff1fd6337e5

**Comment by OmerBenGera** [comment] 2022-07-04 15:24
I dont understand what the issue is

**Comment by Sorusss** [comment] 2022-07-04 16:18
When i put a spawner Insight add me 1 (on the limit) but when i broke him, it does not go down because i use wildstacker spawner

**Comment by OmerBenGera** [comment] 2022-07-04 19:28
> When i put a spawner Insight add me 1 (on the limit) but when i broke him, it does not go down because i use wildstacker spawner

Mind asking the developer of Insights to comment here as well?

**Comment by Sorusss** [comment] 2022-07-04 19:53
okay i will do this, but he told me that was WildStacker problem, and he says in the past you have made a fix version for that

**Comment by FrankHeijden** [comment] 2022-07-04 20:37
Hi Insights mr here
> you have made a fix version for that

No @OmerBenGera didnt make a fix version; but I did create a PR which fixes this issue, which was closed: https://github.com/BG-Software-LLC/WildStacker/pull/320

The issue with WildStacker is essentially that it cancels all BlockBreakEvents in case of a spawner ([here](https://github.com/BG-Software-LLC/WildStacker/blob/b9d6bfade2085093e07f0dc9cd209bf3d7208475/src/main/java/com/bgsoftware/wildstacker/listeners/SpawnersListener.java#L328)), which causes the MONITOR stage for the BlockBreakEvent to not be fired, despite WildStacker setting the block to air ([here](https://github.com/BG-Software-LLC/WildStacker/blob/b9d6bfade2085093e07f0dc9cd209bf3d7208475/src/main/java/com/bgsoftware/wildstacker/listeners/SpawnersListener.java#L113-L114)).

So now we have the case where:
1. BlockBreakEvent MONITOR is not fired;
2. And the block is still "broken"

These events are impossible to detect for other plugins, and a misuse of the Bukkit api; other plugins would like to know when a block is removed as well without throwing a hook to each and every plugin.

**Comment by OmerBenGera** [comment] 2022-07-05 06:32
As I wrote there, use SpawnerPlaceEvent for that. I prefer you to add direct support for WS.

**Comment by FrankHeijden** [comment] 2022-07-05 07:30
> As I wrote there, use SpawnerPlaceEvent for that. I prefer you to add direct support for WS.

I just explained that this is NOT the way things should go to force everyone to use your API. I have zero interest in WildStacker, and don’t want a dangling dependency.

**Comment by OmerBenGera** [comment] 2022-07-05 14:27
> > As I wrote there, use SpawnerPlaceEvent for that. I prefer you to add direct support for WS.
> 
> I just explained that this is NOT the way things should go to force everyone to use your API. I have zero interest in WildStacker, and don’t want a dangling dependency.

Does your plugin have an API or something so I can do it myself? Not sure why you're refusing to add support, but I dont care to do it myself.

**Comment by FrankHeijden** [comment] 2022-07-05 14:47
> > > As I wrote there, use SpawnerPlaceEvent for that. I prefer you to add direct support for WS.
> > 
> > 
> > I just explained that this is NOT the way things should go to force everyone to use your API. I have zero interest in WildStacker, and don’t want a dangling dependency.
> 
> Does your plugin have an API or something so I can do it myself? Not sure why you're refusing to add support, but I dont care to do it myself.

Yes, Insights has an API, but it would be much easier for you to fix this in your plugin than to add support for every plugin which uses the MONITOR event stage.

Insights API is present in the Insights-API folder on GitHub, but this would require you to update the block cache for both the addon storage and world storage, which is much harder than to fix the actual problem.

**Comment by OmerBenGera** [comment] 2022-07-05 18:17
> > > > As I wrote there, use SpawnerPlaceEvent for that. I prefer you to add direct support for WS.
> > > 
> > > 
> > > I just explained that this is NOT the way things should go to force everyone to use your API. I have zero interest in WildStacker, and don’t want a dangling dependency.
> > 
> > 
> > Does your plugin have an API or something so I can do it myself? Not sure why you're refusing to add support, but I dont care to do it myself.
> 
> Yes, Insights has an API, but it would be much easier for you to fix this in your plugin than to add support for every plugin which uses the MONITOR event stage.
> 
> Insights API is present in the Insights-API folder on [GitHub](https://github.com/InsightsPlugin/Insights/tree/master/Insights-API), but this would require you to update the block cache for both the addon storage and world storage, which is much harder than to fix the actual problem.

As I told you before, its not possible to fix it as it would break plugins that support WS and use the SpawnerPlaceEvent. Anyways, it looks too difficult to add aupport for your plugin, and I am not gonna put time into it.

@Sorusss sadly unless @FrankHeijden wont add direct support for WildStacker, they will not work together.

Closing this.

**Closed by OmerBenGera** 2022-07-05 18:17 UTC
Labels: Pending
