### ISSUE TITLE
Plugin Conflict

### ISSUE THREAD

**Issue by deadspidervenom** [BG-Software-LLC/WildStacker#920] opened 2024-06-17 05:20 UTC
### Minecraft's Version

MC 1.20.6
Paper version 1.20.6-113

### Plugin's Version

MCMMO 2.2.012
wildstacker 2024.1 #60

### Describe the bug

Upon mob death no items or exp will drop, stacks will die like a normal mob, and this error will appear every mob death.

```
[20:12:19] [Server thread/WARN]: [WildStacker] Task #1371 for WildStacker v2024.1 generated an exception
java.lang.NoSuchMethodError: 'com.gmail.nossr50.metadata.MetadataService com.gmail.nossr50.mcMMO.getMetadataService()'
	at WildStacker-2024.1.jar/com.bgsoftware.wildstacker.hooks.McMMO210Hook.hasTag(McMMO210Hook.java:102) ~[WildStacker-2024.1.jar:?]
	at WildStacker-2024.1.jar/com.bgsoftware.wildstacker.hooks.McMMO210Hook.isSpawnerEntity(McMMO210Hook.java:98) ~[WildStacker-2024.1.jar:?]
	at WildStacker-2024.1.jar/com.bgsoftware.wildstacker.hooks.McMMO210Hook.handleDeath(McMMO210Hook.java:45) ~[WildStacker-2024.1.jar:?]
	at WildStacker-2024.1.jar/com.bgsoftware.wildstacker.handlers.ProvidersHandler.lambda$notifyEntityDeathListeners$6(ProvidersHandler.java:520) ~[WildStacker-2024.1.jar:?]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596) ~[?:?]
	at WildStacker-2024.1.jar/com.bgsoftware.wildstacker.handlers.ProvidersHandler.notifyEntityDeathListeners(ProvidersHandler.java:520) ~[WildStacker-2024.1.jar:?]
	at WildStacker-2024.1.jar/com.bgsoftware.wildstacker.utils.entity.logic.DeathSimulation.lambda$null$3(DeathSimulation.java:148) ~[WildStacker-2024.1.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.6.jar:1.20.6-113-23fe116]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.6.jar:1.20.6-113-23fe116]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1699) ~[paper-1.20.6.jar:1.20.6-113-23fe116]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:467) ~[paper-1.20.6.jar:1.20.6-113-23fe116]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1571) ~[paper-1.20.6.jar:1.20.6-113-23fe116]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[paper-1.20.6.jar:1.20.6-113-23fe116]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-113-23fe116]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

```

### To Reproduce

Install both MCMMO (not classic) and wild stacker. Kill a mob stacked or not.

### Additional Information

slim chance its a multi mod conflict ill list the other plugins installed. However disabling entity stacking make everything else work as intended.

Citizens, CMILib, DiscordSRV, Essentials, floodgate, Geyser-Spigot, Graves, GSit, Jobs, LevelledMobs
LuckPerms, Quests, SignShop, sleep-most, Vault, ViaVersion, WildTools, WorldEdit
WorldGuard

**Comment by deadspidervenom** [comment] 2024-06-17 05:49
After a bit of research with a friend, turns out the issue is they changed name of some files and locations.

**Comment by deadspidervenom** [comment] 2024-06-18 21:15
> Can confirm. Noticed this a few days ago. This bug occurs on a blank server as well (Only containing McMMO and WildStacker). Another detail is the mobs don't drop any loot, as if though the mob was removed upon death.

> ### Describe the bug
> Upon mob death no **items** or exp will drop, stacks will die like a normal mob, and this error will appear every mob death.

Kinda said that last part in the post lol

**Comment by OmerBenGera** [comment] 2024-06-22 08:52
Duplicate of #921

**Closed by OmerBenGera** 2024-06-22 08:52 UTC
Labels: Pending

**Comment by deadspidervenom** [comment] 2024-06-22 19:35
> Duplicate of #921

umm their post is a duplicate of mine, i posted before them but okay.
