### ISSUE TITLE
Barrel bug - Blocks become normal cauldron

### ISSUE THREAD

**Issue by LoneDevilX** [BG-Software-LLC/WildStacker#315] opened 2021-09-10 09:11 UTC
### Minecraft's Version

Paper version git-Paper-251 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)

### Plugin's Version

WildStacker-b207.jar

### Describe the bug

Barrel sometimes turn into normal cauldron when placing /  work fine when placing, but after while turn into cauldron

### To Reproduce

1. Place the block with [/stacker toggle]
2. Become normal cauldron / become stacked barrel
3. If become stacked barrel, it turns into normal cauldron after awhile or 

### Additional Information

https://cdn.discordapp.com/attachments/554282642980470785/885731776033591316/2021-09-10_06.35.14-1.png

**Comment by OmerBenGera** [comment] 2021-09-10 13:28
Duplicate of #241

**Closed by OmerBenGera** 2021-09-10 13:28 UTC
Labels: Pending
