### ISSUE TITLE
Memorty leak: Stacked entities not getting gc'd

### ISSUE THREAD

**Issue by madmagic007** [BG-Software-LLC/WildStacker#157] opened 2021-04-19 11:08 UTC
**Minecraft's Version**
1.16.5 paper

**Plugin's Version**: -
Both on latest stable 3.5.1 and latest dev 114

**Describe the bug**
Heap size getting really full in lessth an 12hrs because entities that get stacked dont get gc'd. Last time at 14gb memory usage over 600k cows and all the attributes stored in memory. Cows being spawned by spawners using spawnermeta plugin. I dont know if its related to the spawnermeta plugin, all i know is that when i disable entity stacking, the issue doesn't happen.

**To Reproduce**
Have a large amount of spawners (upgraded with spawnermeta, dont know if needed to reproduce) spawning cows, have them stack to one cow before being killed in lava. after some hours of running all the cows that didnt die (stacked) stay in the memory.

**Additional information**
[config.txt](https://github.com/BG-Software-LLC/WildStacker/files/6335471/config.txt)

**Comment by MedicOP** [comment] 2021-04-19 18:08
Same problem here. The HashMap EntityStorage.entityStorage has 31 million entries.

**Comment by MedicOP** [comment] 2021-04-19 18:37
The 31 million values are all EnumMap of size=1 with SpawnCause.SPAWNER as the only entry.

Either the entity removal listener system is not working, or the flags are being added for dead mobs. (World.addEntity never fails but silently sets Entity.dead=true if the mob failed to spawn. Is WildStacker accounting for this?)

**Comment by madmagic007** [comment] 2021-04-20 00:16
Not only that hashmap, but also just "net.minecraft.server.v1_16_R3.EntityCow" has couple hundred thousand entries along with all the pathfinding and other related objects of a cow as seen in [this summary](https://spark.lucko.me/6kqdxm7laj). The summary was taken at 5.5gb total usage, around 7 hrs after last restart. i am unable to make an actualheap dump as itruns on a remote server somewhere and transferring the multi gb file over ftp takes way too long

**Comment by OmerBenGera** [comment] 2021-04-23 14:28
`In NMSSpawners_v1_8_R3.handleEntitySpawn for example it calls EntityStorage.setMetadata() then calls World.addEntity() couple lines after. The entity might never get added to the world and thus cause memory leak.`
I'll try to add a check for that, but I also want you to try and disable spawners-override so WildStacker doesn't handle spawners, and check if it still works as it should. If it doesn't, then it's not the cause and we'll have to find what else can do that

**Comment by OmerBenGera** [comment] 2021-04-23 14:42
I uploaded a new version that might fix the issue.
Let me know how it works on your server (If you do it by tomorrow, I'll be able to respond quickly)

**Comment by MedicOP** [comment] 2021-04-23 15:41
Already tried fixing it myself because it was taking too long, seems to be working so far. The code in the latest commit looks like it should do the same

**Comment by OmerBenGera** [comment] 2021-04-23 15:59
> 
> 
> Already tried fixing it myself because it was taking too long, seems to be working so far. The code in the latest commit looks like it should do the same

Yeah I am not active as I used to be, that's the reason the plugin is open source so others can help as well.
Not sure what you meant, but do you believe the last update should fix it?

**Comment by MedicOP** [comment] 2021-04-23 17:12
> Not sure what you meant, but do you believe the last update should fix it?

yep

**Comment by madmagic007** [comment] 2021-04-25 09:37
using the latest dev version, still same issue https://spark.lucko.me/#owNASDTovq

**Comment by MedicOP** [comment] 2021-04-25 19:51
it's not fixed for me either

**Comment by MedicOP** [comment] 2021-04-25 19:57
I think removeStackObject is not being called because the stackedEntity is null in NMSSpawners.

My own fix (which did work) calls EntityStorage.clearMetadata(bukkitEntity) instead of relying on removeStackObject in NMSSpawners.handleEntitySpawn()

Also I added this scheduled call in SpawnersListener.onSpawnerSpawn()

```java
        EntityStorage.setMetadata(e.getEntity(), EntityFlag.SPAWN_CAUSE, SpawnCause.SPAWNER);

        Bukkit.getScheduler().runTask(plugin, () -> {
            if (e.getEntity().isDead()) {
                EntityStorage.clearMetadata(e.getEntity());
            }
        });
```

**Comment by OmerBenGera** [comment] 2021-04-30 16:12
I pushed a new update, let me know how it handles it now
I implemented your changes, however I checked the return value of addEntity instead of checking if the entity is dead.
Also, as you might have seen, I am not that active, so PR are always welcome :)

**Comment by OmerBenGera** [comment] 2021-05-07 11:35
@MedicOP Any news?

**Comment by OmerBenGera** [comment] 2021-05-07 15:54
I implemented the exact same solution you gave that you said that fixes the issues...

**Comment by MedicOP** [comment] 2021-05-07 16:06
OR it was something else, also possible.. did not bother making a heap dump as the season was almost over

you can close this if you want. i'll make a PR in the future if it's still happening next season

**Comment by OmerBenGera** [comment] 2021-05-07 16:17
Keeping this opened for now

**Comment by madmagic007** [comment] 2021-05-13 00:36
sorry i did not get to test it on my server anymore, i found a workaround that doesnt need the stacking for my server. however i do believe i foudn another issue, but that could be a config thing: when stackable buckets is enabled and stacked buckets are in a chest and the chects is destroyed, it only drops 1 bucket

**Comment by OmerBenGera** [comment] 2021-05-14 10:37
> 
> 
> sorry i did not get to test it on my server anymore, i found a workaround that doesnt need the stacking for my server. however i do believe i foudn another issue, but that could be a config thing: when stackable buckets is enabled and stacked buckets are in a chest and the chects is destroyed, it only drops 1 bucket

Sounds like a bug with Minecraft itself.
Anyways, I am closing this for now, as I can't seem to replicate the issue and I don't see a reason why it won't work.

**Closed by OmerBenGera** 2021-05-14 10:37 UTC
Labels: Bug Report, Further Investigation
