### ISSUE TITLE
Mining Spawners

### ISSUE THREAD

**Issue by NuggetDesign** [BG-Software-LLC/WildStacker#448] opened 2022-02-06 22:13 UTC
### Minecraft's Version

1.18.1-R0.1-Snapshoot Paper(115)

### Plugin's Version

Dev build 274

### Describe the bug

players are unable to mine spawners either from silktouch or non silktouch. I gave perms and tested enabled silktouch and disabling it. All doesnt work

### To Reproduce

Enable silktouch (doesnt work)
Disable silktouch, giveperm (doesnt work)

**Comment by OmerBenGera** [comment] 2022-02-07 18:16
Duplicate of #447

**Closed by OmerBenGera** 2022-02-07 18:16 UTC
Labels: Pending

**Comment by NuggetDesign** [comment] 2022-02-07 19:02
duplicate? meaning do not report the same thing?
