### ISSUE TITLE
Cauldrons will fill with water, changing block id, and loose the stack data.

### ISSUE THREAD

**Issue by MamaBeau** [BG-Software-LLC/WildStacker#267] opened 2021-08-15 00:33 UTC
### Minecraft's Version

1.17.1

### Plugin's Version

3.6.0-DEVb184

### Describe the bug

A stacked cauldron will fill up with rain (normal behavior) and I guess change the block data, this caused the cauldron to loose its stack data. The stack numbers will still be above the cauldron but the item will not me.
When breaking the cauldron it will leave the holo there until a restart. 

### To Reproduce

Place a caudron, make it rain and wait. We waited over 30 minutes at one point and thought it was okay. Closed the bug report, the player went and did other things then came back to the location and the cauldron was filled with water and the data removed.

### Additional Information

none

**Comment by OmerBenGera** [comment] 2021-08-15 08:37
Duplicate of #241

**Closed by OmerBenGera** 2021-08-15 08:37 UTC
Labels: Bug Report, Pending
