### ISSUE TITLE
Dupe issue with stacker and slimefun

### ISSUE THREAD

**Issue by amarcais53** [BG-Software-LLC/WildStacker#151] opened 2021-04-11 16:21 UTC
**Minecraft's Version**

![image](https://user-images.githubusercontent.com/62488520/114312207-29dc5200-9af2-11eb-99a2-64d7fa988d85.png)

**Plugin's Version**: -
DEV build 106
And latest slimefun
**Describe the bug**
When i take a machine from slimefun caled auto anvil (iron block texture) and i do /stacker toggle and then place it to the barrel the machine is going on the barrel and when i break the barrel its giving me the machine and a iron block instead of just 1 machine 

**To Reproduce**
There is a quick video to reproduce it
you need aswell slimefun installed on the server
https://www.youtube.com/watch?v=YeiOMEi89GM

**Additional information**
N/A

**Comment by OmerBenGera** [comment] 2021-04-15 09:30
The issue is because Slimefun still things the item is there, and therefore it also drops the item while WS does the same.
I will look what can be done on my side to fix the issue

**Comment by amarcais53** [comment] 2021-04-15 15:42
thank you aswell

**Comment by OmerBenGera** [comment] 2021-04-16 15:28
@amarcais53 Check out latest dev build, let me know if it fixes the issue

**Comment by amarcais53** [comment] 2021-04-16 17:46
i will tell you tomorrow after the server restart

**Comment by amarcais53** [comment] 2021-04-17 22:19
@OmerBenGera the bug is partialy fixed now there is no dupe bug but when we put Slimefun machine with the shift right click option its stacking it and when we break we get iron block but no machine https://www.youtube.com/watch?v=t9SFFf4PQJI

**Comment by OmerBenGera** [comment] 2021-05-07 12:08
Fixed in latest dev build

**Closed by OmerBenGera** 2021-05-07 12:08 UTC
Labels: Bug Report, Confirmed
