### ISSUE TITLE
Could not pass event PreSpawnerSpawnEvent to WildStacker v3.6.0-DEVb217

### ISSUE THREAD

**Issue by Gida4** [BG-Software-LLC/WildStacker#345] opened 2021-10-10 17:13 UTC
### Minecraft's Version

Purpurclip 1.17.1  build 1404

### Plugin's Version

v3.6.0-DEVb217

### Describe the bug

[19:07:30] [Server thread/ERROR]: Could not pass event PreSpawnerSpawnEvent to WildStacker v3.6.0-DEVb217
java.lang.NoSuchMethodError: 'void org.bukkit.craftbukkit.v1_17_R1.block.CraftBlockEntityState.<init>(org.bukkit.block.Block, java.lang.Class)'
        at com.bgsoftware.wildstacker.nms.NMSAdapter_v1_17_R1$SyncedCreatureSpawnerImpl.<init>(NMSAdapter_v1_17_R1.java:1158) ~[WildStacker.jar:?]
        at com.bgsoftware.wildstacker.nms.NMSAdapter_v1_17_R1.createSyncedSpawner(NMSAdapter_v1_17_R1.java:567) ~[WildStacker.jar:?]
        at com.bgsoftware.wildstacker.utils.spawners.SyncedCreatureSpawner.of(SyncedCreatureSpawner.java:13) ~[WildStacker.jar:?]
        at com.bgsoftware.wildstacker.objects.WStackedSpawner.<init>(WStackedSpawner.java:47) ~[WildStacker.jar:?]
        at com.bgsoftware.wildstacker.objects.WStackedSpawner.<init>(WStackedSpawner.java:43) ~[WildStacker.jar:?]
        at com.bgsoftware.wildstacker.handlers.SystemHandler.getStackedSpawner(SystemHandler.java:252) ~[WildStacker.jar:?]
        at com.bgsoftware.wildstacker.handlers.SystemHandler.getStackedSpawner(SystemHandler.java:241) ~[WildStacker.jar:?]
        at com.bgsoftware.wildstacker.objects.WStackedSpawner.of(WStackedSpawner.java:60) ~[WildStacker.jar:?]
        at com.bgsoftware.wildstacker.objects.WStackedSpawner.of(WStackedSpawner.java:55) ~[WildStacker.jar:?]
        at com.bgsoftware.wildstacker.listeners.SpawnersListener$PaperSpawnersListener.onPreSpawnSpawner(SpawnersListener.java:734) ~[WildStacker.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[patched_1.17.1.jar:git-Purpur-1404]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.17.1.jar:git-Purpur-1404]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1404]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[patched_1.17.1.jar:git-Purpur-1404]
        at org.bukkit.event.Event.callEvent(Event.java:45) ~[patched_1.17.1.jar:git-Purpur-1404]
        at net.minecraft.world.level.BaseSpawner.serverTick(BaseSpawner.java:148) ~[app:?]
        at net.minecraft.world.level.block.entity.SpawnerBlockEntity.serverTick(SpawnerBlockEntity.java:56) ~[app:?]
        at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.a(LevelChunk.java:1491) ~[app:?]
        at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.a(LevelChunk.java:1443) ~[app:?]
        at net.minecraft.world.level.Level.tickBlockEntities(Level.java:1124) ~[app:?]
        at net.minecraft.server.level.ServerLevel.tickCustomSpawners(ServerLevel.java:821) ~[app:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1644) ~[patched_1.17.1.jar:git-Purpur-1404]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:518) ~[patched_1.17.1.jar:git-Purpur-1404]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1499) ~[patched_1.17.1.jar:git-Purpur-1404]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1292) ~[patched_1.17.1.jar:git-Purpur-1404]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-1404]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]

### To Reproduce

I do not know. It repeats all the time.

**Comment by OmerBenGera** [comment] 2021-10-11 03:54
Duplicate of #341

**Closed by OmerBenGera** 2021-10-11 03:54 UTC
Labels: Pending
