### ISSUE TITLE
EntityDamageEvent - EventException: null

### ISSUE THREAD

**Issue by TheJoshue** [BG-Software-LLC/WildStacker#996] opened 2024-12-26 23:05 UTC
### Minecraft's Version

Pandaspigot 1.8.8

### Plugin's Version

2024.4-b110

### Describe the bug

https://mclo.gs/e82MU6X
Simply run the plugin and this pops up

### To Reproduce

https://mclo.gs/e82MU6X
Simply run the plugin and this pops up

**Comment by OmerBenGera** [comment] 2024-12-27 07:35
Duplicate of #993

**Closed by OmerBenGera** 2024-12-27 07:35 UTC
Labels: Pending

**Comment by TheJoshue** [comment] 2024-12-28 15:02
Hello there
tested with b133
https://mclo.gs/GCMvKoh

**Comment by TheJoshue** [comment] 2024-12-28 16:59
> Hello there tested with b113 Error now: https://mclo.gs/GCMvKoh

i apologize, this was tested on paid fork Carbon -- this is the only error happening when using Carbon(Spigot) 1.8.8

When using PandaSpigot this is the error, tested with b113:
https://mclo.gs/uhZsfZa

**Comment by TheJoshue** [comment] 2025-01-04 17:32
using Carbon 1.8.8
https://mclo.gs/X2DVEac

Any ideas @OmerBenGera what we could test to have more info for potential fix?
Thank you in advance and sorry for bothering

**Comment by OmerBenGera** [comment] 2025-01-04 21:56
Check out #993 , waiting for someone to give me their config file which causes these errors
