### ISSUE TITLE
Spawner Limits 

### ISSUE THREAD

**Issue by YouSeeMeRunning2** [BG-Software-LLC/WildStacker#402] opened 2021-12-22 18:03 UTC
### Minecraft's Version

1.16.5

### Plugin's Version

#244

### Describe the bug

https://pastebin.com/czJ0x9vZ

Unable to get spawner limits to work correctly, I want a spawner to merge in a chunk to 500. 

Once the spawner reaches 500 the player can create another spawner stack within the chunk

### To Reproduce

Follow config

**Comment by OmerBenGera** [comment] 2021-12-22 18:24
Chunk limits check for individual spawners and doesnt care about the amount of spawners in the stack. Also, ypu have a chunk limit of 0, so you technically dont even have a limit for your chunks.
Closing this, not a bug.

**Closed by OmerBenGera** 2021-12-22 18:24 UTC
Labels: Pending
