### ISSUE TITLE
Spawners Get Set To 1

### ISSUE THREAD

**Issue by zolvity** [BG-Software-LLC/WildStacker#131] opened 2021-03-31 00:05 UTC
**Minecraft's Version**
SpaceDelaSpigot 1.8.8

**Plugin's Version**: -
WildStacker-b103

**Describe the bug**
Everytime the server restarts all spawners get set to 1

**To Reproduce**
Steps to reproduce the bug.

**Additional information**
Everytime i restart the server all my players spawners get set to 1

**Comment by OmerBenGera** [comment] 2021-03-31 13:22
Duplicate of #38

**Closed by OmerBenGera** 2021-03-31 13:22 UTC
Labels: Bug Report, Pending
