### ISSUE TITLE
Why Villager can not Breeding?

### ISSUE THREAD

**Issue by Peeraboon** [BG-Software-LLC/WildStacker#181] opened 2021-05-31 15:09 UTC
**Minecraft's Version**
This server is running Purpur version git-Purpur-1151 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are running the latest version

**Plugin's Version**: -
WildStacker-b131

**Describe the bug**
Villager cannot breed.

**To Reproduce**
Breed Villager

**Additional information**
default plugin config and server config
Video: https://www.youtube.com/watch?v=64EkyQ8o0aY

**Comment by OmerBenGera** [comment] 2021-06-04 17:53
I am not sure why, but the villagers are getting angry in the process of the breeding (even without WildStacker installed)
Does anybody know why it happens, so I can manage to replicate the issue?

**Comment by OmerBenGera** [comment] 2021-06-12 17:18
@Peeraboon maybe you know why it happens?

**Comment by Peeraboon** [comment] 2021-06-12 17:29
> @Peeraboon maybe you know why it happens?

Not sure does it still happen or not. I haven't changed anything.
Maybe I will test it again on plain server today.

**Comment by OmerBenGera** [comment] 2021-06-12 17:54
> 
> 
> > @Peeraboon maybe you know why it happens?
> 
> Not sure does it still happen or not. I haven't changed anything.
> Maybe I will test it again on plain server today.

Great. If there's still an issue, check out my question above

**Comment by Peeraboon** [comment] 2021-06-13 06:17
> > > @Peeraboon maybe you know why it happens?
> > 
> > 
> > Not sure does it still happen or not. I haven't changed anything.
> > Maybe I will test it again on plain server today.
> 
> Great. If there's still an issue, check out my question above

I have tested it 2 times.
When I use the default plugin config the villager can't breed but if I disable the items stack in config.

`# Here you can configurable all features related to stacked items.
items:
  # Should items get stacked on the server?
  enabled: false`

The villager can breed.

**Comment by Peeraboon** [comment] 2021-06-13 06:19
First, I use every thing in default. The villager cannot breed but if i disable item stack in config

# Here you can configurable all features related to stacked items.
items:
  # Should items get stacked on the server?
  enabled: false


The Villager can breed

**Comment by Peeraboon** [comment] 2021-06-13 06:20
First, I use every thing in default. The villager cannot breed but if i disable item stack in config

`items:
  enabled: false`

The Villager can breed

**Comment by Peeraboon** [comment] 2021-06-13 06:20
First, I use every thing in default. The villager cannot breed but if i disable item stack in config

items:
  enabled: false

The Villager can breed

**Comment by Peeraboon** [comment] 2021-06-13 06:21
> > > @Peeraboon maybe you know why it happens?
> > 
> > 
> > Not sure does it still happen or not. I haven't changed anything.
> > Maybe I will test it again on plain server today.
> 
> Great. If there's still an issue, check out my question above

First, I use every thing in default. The villager cannot breed but if i disable item stack in config

items:
enabled: false

The Villager can breed

**Comment by OmerBenGera** [comment] 2021-06-18 10:13
> I am not sure why, but the villagers are getting angry in the process of the breeding (even without WildStacker installed)
> Does anybody know why it happens, so I can manage to replicate the issue?

**Comment by amarcais53** [comment] 2021-06-18 14:31
i have the same isssue
villagers need to have 3 bed for 2 villagers and a job like farmer @OmerBenGera 
if u want to replicate copy what i do on this video https://www.youtube.com/watch?v=iAZ6ZW6mVWQ

**Comment by OmerBenGera** [comment] 2021-06-19 08:36
I can't manage to get the villagers to breed even without WildStacker.
Unless anybody tell me what I am doing wrong, I won't be able to get it fixed.

**Comment by amarcais53** [comment] 2021-06-19 13:56
Send us a screen shot of your farm please @OmerBenGera

**Comment by OmerBenGera** [comment] 2021-06-19 18:34
> 
> 
> Send us a screen shot of your farm please @OmerBenGera

There is no farm nearby. Only 3 beds and 3 workstations with 2 villagers nearby.
They can't breed even tho they start the process.

**Comment by amarcais53** [comment] 2021-06-19 18:36
Try with composter instead of workstation and add something for them to harvest

**Comment by amarcais53** [comment] 2021-06-19 18:37
And the thing is when item stacker is activated the cannot breed so make sure un disable it before

**Comment by Skizzles** [comment] 2021-06-19 22:26
@Peeraboon
@OmerBenGera
@amarcais53

do you have mobgriefing on or off?

**Comment by amarcais53** [comment] 2021-06-19 23:13
mobgriefing is on @Skizzles

**Comment by amarcais53** [comment] 2021-06-19 23:13
it was working before but i cant fingure since what update it not work anymore

**Comment by Skizzles** [comment] 2021-06-20 01:15
I would check ur specific world gamerules, villager breeding from dropping items does NOT work when mobgriefing gamerule is set to off.

Otherwise I would provide what build of purpur you are on. Purpur has settings that change villager behavior so this could also be causing an issue.

could try with paper instead of purpur etc.

**Comment by amarcais53** [comment] 2021-06-20 01:17
again and i said it before when we disable item stacking everything works fine so i doubt its an issue with purpur or gamerule because it was working a month ago

**Comment by Skizzles** [comment] 2021-06-20 01:19
> again and i said it before when we disable item stacking everything works fine so i doubt its an issue with purpur or gamerule because it was working a month ago

Again, try it on paper and let me know if it still occurs. That way we can rule out it being based off the server jar / settings.

**Comment by amarcais53** [comment] 2021-06-20 01:21
ok im trying that now

**Comment by amarcais53** [comment] 2021-06-20 01:27
[https://www.youtube.com/watch?v=U9o3yJwC9RY](url)

**Comment by amarcais53** [comment] 2021-06-20 01:28
there is with paper

**Comment by klaidoshka** [comment] 2021-06-20 08:33
Well....
- mobGriefing - enabled;
- Default server platform (Paper and every other after it);
- No WildStacker inside, no plugins (and even if WildStacker is inside the plugins with on top mentioned "items-stacking: false" setting).

The villagers just DO NOT breed 🤣, no idea when this happened, but I guess it was either Spigot's or Paper's doing, because every server platform has this thing with default (unchanged) settings.

***I didn't test Spigot**

So I guess it has absolutely nothing to do with WildStacker, only server platforms, we should write to those devs. 👀 Also, if what Peeraboon said (below) is true, then the breeding just became omega-super rarely and it has nothing to do with WildStackers' setting.

> First, I use every thing in default. The villager cannot breed but if i disable item stack in config
> items:
> enabled: false
> The Villager can breed

**Comment by amarcais53** [comment] 2021-06-20 09:09
So how did you explain that it works for me and when I enable item stacker it doesn’t

**Comment by klaidoshka** [comment] 2021-06-20 10:20
No clue? I never saw you showing that it works for you with item-stacking disabled.
And if it works, what build of your server platform are you using? Purpur-b1156 ?

**Comment by amarcais53** [comment] 2021-06-20 10:38
Im using purpur I tried with paper I have the same issue

**Comment by Peeraboon** [comment] 2021-06-20 10:42
I have tried it again. I use latest purpur build(1171) and latest Wildstacker b142 with everything in default
and only Wildstacker-b142 installed on the server.
And got the same result as before

> 
> First, I use every thing in default. The villager cannot breed but if i disable item stack in config
> 
> items:
> enabled: false
> 
> The Villager can breed

If I disable item-stack it will work. May be there is a problem with item-stack? I just guess

**Comment by amarcais53** [comment] 2021-06-20 10:49
Oh yeah sorry that what I mean ahah it’s the item stacker when u disable it and just reload it works

**Comment by klaidoshka** [comment] 2021-06-20 11:25
No clue, for us it doesn't work in both ways.

By both ways I mean:
Without WildStacker, with WildStacker and itemstacking (no idea how it depends on entities breeding) being disabled.

**Comment by amarcais53** [comment] 2021-06-20 11:27
could you try with these setttings ? 
[Nouveau Archive WinRAR ZIP.zip](https://github.com/BG-Software-LLC/WildStacker/files/6682188/Nouveau.Archive.WinRAR.ZIP.zip)

**Comment by amarcais53** [comment] 2021-06-20 11:28
its my paper spigot and bukkit YML

**Comment by amarcais53** [comment] 2021-06-20 11:28
they are optimized and could you do  a video of your farm to see if you do everything corectly

**Comment by klaidoshka** [comment] 2021-06-20 12:54
> 
> 
> they are optimized and could you do a video of your farm to see if you do everything corectly

Okay, learned a bit about villagers (until now was playing in old 1.8.8 version and knew almost nothing about 1.9+ stuff).
So, the problem was that I had too little amount of beds for the villagers, after putting more of beds, they started spawning. So it's not a problem of server platform.

Everything worked without WildStacker and with WildStacker (while `item-stacking` was `disabled`).

However, when item-stacking is enabled, breeding doesn't work anymore, they don't even try to breed (while when having `item-stacking disabled` they do try to), meaning that somehow those villagers 'think' that they didn't get a certain amount of food or something and they don't even bother breeding, even though I gave dozens of stacks to different villagers, they still didn't try to breed. Something isn't right. Smart-breeding option in config.yml doesn't help here, because it is made for animals.

@OmerBenGera

**Comment by amarcais53** [comment] 2021-06-20 14:19
i suggest you to watch my video where we can see that i droped about 20 stacks of carrots and the inventory of viallgers was empty so the thing is they grab the items but items are not going on villagers inventory you can check there https://www.youtube.com/watch?v=U9o3yJwC9RY

**Comment by OmerBenGera** [comment] 2021-06-25 11:05
I am trying to replicate the issue now, hopefully I'll be able to get the villagers to breed with each other (without WildStacker for now)

**Comment by OmerBenGera** [comment] 2021-06-25 11:24
I managed to get villagers to breed with WildStacker installed and items stacking enabled on Spigot 1.17

**Comment by amarcais53** [comment] 2021-06-25 11:39
did u killed them after enabling WS ?
and then repsawned them

**Comment by amarcais53** [comment] 2021-06-25 11:39
because the thing is when its enable they cant take the food on the ground
but if they already have it on inventory it will work
so kill them respawn them and try

**Comment by amarcais53** [comment] 2021-06-25 11:40
@OmerBenGera

**Comment by amarcais53** [comment] 2021-06-25 11:50
the step to do it is kill villagers , enbale item stack, spawn them , drop them carrots they are gonna take it but not breed

**Comment by amarcais53** [comment] 2021-06-25 23:06
do you want me to make a full video for u with the fresh server install without any plugin to show you ?

**Comment by OmerBenGera** [comment] 2021-06-26 18:22
I am using latest WildStacker, I spawned new villagers and it worked just fine.
I placed a lot of beds and had the villagers have no professions.

**Comment by amarcais53** [comment] 2021-06-26 19:03
ok im rendering video for you its a bit long video because i show you the fresh server instal u will see and maybe understand what i am saying ^^

**Comment by amarcais53** [comment] 2021-06-26 19:17
@OmerBenGera here is the video please try it as same i do it https://www.youtube.com/watch?v=9dflqiokOtk

**Comment by OmerBenGera** [comment] 2021-06-27 04:49
> @OmerBenGera here is the video please try it as same i do it https://www.youtube.com/watch?v=9dflqiokOtk

Try that without the villagers being farmers.

**Comment by amarcais53** [comment] 2021-06-27 05:03
it doesnt works :/ should i send you video ? did u try it on 1.16.5 ?

**Comment by amarcais53** [comment] 2021-06-27 05:09
i also tried to remove shopkeeper so there was only Wildstacker on the server and it didnt works they just standing and doing nothing

**Comment by amarcais53** [comment] 2021-06-27 05:27
OHOHOH i have some news i tested on spigot 1.17 latest and it works so the issue is on 1.16.5

**Comment by OmerBenGera** [comment] 2021-07-02 15:29
I managed to replicate the issue on latest version of Paper for 1.16.5.
I am gonna look into that and fix it.

**Comment by amarcais53** [comment] 2021-07-02 15:42
Oh glad to hear that thank you

**Comment by OmerBenGera** [comment] 2021-07-02 16:03
Should be fixed in dev build 149.
Let me know if it works for you as well.

**Comment by amarcais53** [comment] 2021-07-02 16:46
hum interesting it seems to be partialy fixed , when i start the server and give them carrots they are taking it but if i wait 1 min and then give them again they are not taking anymore

**Comment by amarcais53** [comment] 2021-07-02 18:06
i recomand you to use shopkeeper to see villagers inventory

**Comment by OmerBenGera** [comment] 2021-07-02 18:15
> 
> 
> hum interesting it seems to be partialy fixed , when i start the server and give them carrots they are taking it but if i wait 1 min and then give them again they are not taking anymore

I don't think it's related to WildStacker, but I'll check that out.
Also, there's no need to use plugins in order to see villagers inventory, the command /data exists in game and already does that.

**Comment by amarcais53** [comment] 2021-07-02 18:18
oh great glad to hear that i can now remove 1 more plugin ahah i hope u will find something

**Comment by OmerBenGera** [comment] 2021-07-02 18:23
They seem to pickup more items just fine, mind taking a video maybe?

**Comment by amarcais53** [comment] 2021-07-02 18:23
can we maybe screeshar on discord

**Comment by amarcais53** [comment] 2021-07-02 18:24
it would be more faster and understandable for u

**Comment by OmerBenGera** [comment] 2021-07-02 18:29
> 
> 
> can we maybe screeshar on discord

Sadly no, it is not possible.
I prefer if you upload a video to YT or any other streaming service so I can look at that.

**Comment by amarcais53** [comment] 2021-07-02 18:49
ok i found something that should really help you sorry about my bad english as you can see  i'm french and french people (most of them)  doesn't know how to speak english xD  https://www.youtube.com/watch?v=cuIE9ef1QIk

**Comment by amarcais53** [comment] 2021-07-02 18:50
@OmerBenGera

**Comment by OmerBenGera** [comment] 2021-07-02 20:46
Tbh, that's a bug with Paper.
In older versions of Paper, when the pickup event was cancelled, they weren't removing the item that was picked up. They tried to fix it, and it works unless the item that is picked up is not added as a new stack, but an item is changed. When this happens, and they restore the inventory with the original contents, the items that were modified are still modified, and therefore "part" of the picked up item is still in the inventory even if the event is cancelled.
Contact paper developers so they can fix it. They fixed it completely in 1.17 by making a clone of the inventory and add the item there, and they only modify the inventory after the event, which makes the inventory to not get modified before the event.

Due to that, I am closing this issue for now. I will keep the patch in the plugin, even tho it doesn't work 100% of the time, and there are issues when items are not added as new stacks (as seen in your video).

**Closed by OmerBenGera** 2021-07-02 20:46 UTC
Labels: Bug Report, Potential fix

**Comment by amarcais53** [comment] 2021-07-02 20:48
Could you report them please because I’m not really friendly with that I’m bad at coding

**Comment by amarcais53** [comment] 2021-07-02 20:49
and I don’t even understand what you saying lol

**Comment by amarcais53** [comment] 2021-07-02 20:51
Last time I reported them something with stacker they said don’t use stacker and they banned  me from discord

**Comment by OmerBenGera** [comment] 2021-07-02 20:54
I will make a bug report about that.

**Comment by amarcais53** [comment] 2021-07-02 20:54
Thank you ❤️

**Comment by OmerBenGera** [comment] 2021-07-02 21:07
You may find progress about the issue here:
https://github.com/PaperMC/Paper/issues/6068
