### ISSUE TITLE
Console Error on spawn event

### ISSUE THREAD

**Issue by tashak700** [BG-Software-LLC/WildStacker#104] opened 2021-03-30 15:28 UTC
[15:06:47 ERROR]: Could not pass event CreatureSpawnEvent to WildStacker v3.5.1-DEVb101
java.lang.NullPointerException: null
        at com.bgsoftware.wildstacker.listeners.EntitiesListener.lambda$onEntitySpawnLow$7(EntitiesListener.java:521) ~[?:?]
        at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
        at com.bgsoftware.wildstacker.listeners.EntitiesListener.onEntitySpawnLow(EntitiesListener.java:519) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor640.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-499]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-499]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-499]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-499]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:698) ~[patched_1.16.5.jar:git-Paper-499]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:619) ~[patched_1.16.5.jar:git-Paper-499]
        at net.minecraft.server.v1_16_R3.WorldServer.addEntity0(WorldServer.java:1188) ~[patched_1.16.5.jar:git-Paper-499]
        at net.minecraft.server.v1_16_R3.WorldServer.addEntity(WorldServer.java:1089) ~[patched_1.16.5.jar:git-Paper-499]
        at net.minecraft.server.v1_16_R3.EntitySlime.die(EntitySlime.java:223) ~[patched_1.16.5.jar:git-Paper-499]
        at net.minecraft.server.v1_16_R3.EntityLiving.cU(EntityLiving.java:467) ~[patched_1.16.5.jar:git-Paper-499]
        at net.minecraft.server.v1_16_R3.EntityLiving.entityBaseTick(EntityLiving.java:342) ~[patched_1.16.5.jar:git-Paper-499]
        at net.minecraft.server.v1_16_R3.EntityInsentient.entityBaseTick(EntityInsentient.java:247) ~[patched_1.16.5.jar:git-Paper-499]
        at net.minecraft.server.v1_16_R3.Entity.tick(Entity.java:406) ~[patched_1.16.5.jar:git-Paper-499]
        at net.minecraft.server.v1_16_R3.EntityLiving.tick(EntityLiving.java:2449) ~[patched_1.16.5.jar:git-Paper-499]
        at net.minecraft.server.v1_16_R3.EntityInsentient.tick(EntityInsentient.java:310) ~[patched_1.16.5.jar:git-Paper-499]
        at net.minecraft.server.v1_16_R3.EntitySlime.tick(EntitySlime.java:116) ~[patched_1.16.5.jar:git-Paper-499]
        at net.minecraft.server.v1_16_R3.WorldServer.entityJoinedWorld(WorldServer.java:846) ~[patched_1.16.5.jar:git-Paper-499]
        at net.minecraft.server.v1_16_R3.World.a(World.java:886) ~[patched_1.16.5.jar:git-Paper-499]
        at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:531) ~[patched_1.16.5.jar:git-Paper-499]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1362) ~[patched_1.16.5.jar:git-Paper-499]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.5.jar:git-Paper-499]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1214) ~[patched_1.16.5.jar:git-Paper-499]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1002) ~[patched_1.16.5.jar:git-Paper-499]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Paper-499]
        at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by tashak700** [comment] 2021-03-30 15:31
Version: Paper version git-Paper-499 (MC 1.16.5) (Implementing API version 1.16.5-R.01-SNAPSHOT)

WildStacker Version: b101

**Comment by OmerBenGera** [comment] 2021-03-30 15:37
Open issues with the format for the next time please.
About the error - mind using latest dev build and if it happens again, send the error again?

**Comment by ElBananaa** [comment] 2021-04-02 16:04
Hey!
I have the same issue than the author. I don't know when this happen, so I won't be able to provide a description. However, I can tell it happens almost every 10 minutes, and it sometimes spams the console for 1/2 minutes. Since I don't know when this exactly happen I can't tell any steps to reproduce, however, I think that it happens when you're near a spawner and a mob spawns.

Version : Purpur version git-Purpur-1051 (MC: 1.16.5)
Plugin Version : WildStacker-b103
Error log : https://paste.gg/p/anonymous/677999c826384b539e9b81e8feed5418

**Comment by ElBananaa** [comment] 2021-04-04 04:26
Hey!
Quick update: I updated the plugin to the build 106 a few hours ago, and now it constantly spams the console with this error: https://paste.gg/p/anonymous/25f56b8c0ecd4195b1b3dd53c10deedc
I've got around 40k lines of errors in only 4 hours.

**Comment by OmerBenGera** [comment] 2021-04-10 06:02
Fixed in build 107

**Closed by OmerBenGera** 2021-04-10 06:02 UTC
Labels: Bug Report, Further Investigation
