### ISSUE TITLE
Weird console error

### ISSUE THREAD

**Issue by Rhys00** [BG-Software-LLC/WildStacker#613] opened 2022-09-19 13:08 UTC
### Minecraft's Version

PaperMC 1.8.8

### Plugin's Version

2022.5-b359

### Describe the bug

When I placed a cow spawner and killed a cow this error popped up in console (https://paste.helpch.at/ataxeyarah.rb) and then the cow become invincible and wouldnt die.

### To Reproduce

Place mob spawner down, kill first mob and then the error should pop up.

**Comment by OmerBenGera** [comment] 2022-09-19 16:23
Duplicate of #473

**Closed by OmerBenGera** 2022-09-19 16:23 UTC
Labels: Pending
