### ISSUE TITLE
Unbeatable Mobs Issue

### ISSUE THREAD

**Issue by ItzFabb-uwu** [BG-Software-LLC/WildStacker#615] opened 2022-09-20 14:49 UTC
### Minecraft's Version

Wine Spigot v3913
Minecraft Version: 1.8.8

### Plugin's Version

![image](https://user-images.githubusercontent.com/58950562/191289472-bcfe5b5a-2bab-45e7-a81c-cc0a261aecd5.png)

### Describe the bug

So whenever a mob/animals get stacked and 1 of the stacked entities got killed the rest of the stacker mobs just seems to be unkillable and has unlimited health...

### To Reproduce

| Place 1 any of the mobs type (1st)

| And then wait till the mob get stacked (2nd)

| Try to kill 1 of the stacked entities (3rd)

### Additional Information

https://youtu.be/hicytJvS3bQ

**Comment by ItzFabb-uwu** [comment] 2022-09-20 15:27
https://youtu.be/COIVccX6tjg | 2 Plugins with winespigot jar
1.8.8

**Comment by OmerBenGera** [comment] 2022-09-20 17:03
Errors?

**Comment by ItzFabb-uwu** [comment] 2022-09-20 17:22
> Errors?

There are no errors in the wildstacker

**Comment by ItzFabb-uwu** [comment] 2022-09-20 17:23
I've also tried to only use wildstacker and viaversion on 2nd server and the result is the same the issue is not because of the others plugin :/

**Comment by OmerBenGera** [comment] 2022-09-20 17:47
Show me your server logs.
I know that it happens when an error occurs.

**Comment by ItzFabb-uwu** [comment] 2022-09-21 02:00
> Show me your server logs. I know that it happens when an error occurs.

https://mcpaste.io/4ddc54ea02a7f4cf

**Comment by ItzFabb-uwu** [comment] 2022-09-21 04:48
> Is it because of this issue? idk i'm using the default configuration for the wildstacker


20.09 16:25:29 [Server] [WARN] [WildStacker] Task #205 for WildStacker v2022.5-b359 generated an exception
20.09 16:25:29 [Server] [INFO] java.lang.IllegalArgumentException: The entity-type EXPERIENCE_ORB is not a stackable entity.
20.09 16:25:29 [Server] [INFO] at com.bgsoftware.wildstacker.objects.WStackedEntity.of(WStackedEntity.java:76) ~[?:?]
20.09 16:25:29 [Server] [INFO] at com.bgsoftware.wildstacker.nms.v1_8_R3.NMSAdapter.createEntity(NMSAdapter.java:128) ~[?:?]
20.09 16:25:29 [Server] [INFO] at com.bgsoftware.wildstacker.nms.v1_8_R3.NMSAdapter.spawnExpOrb(NMSAdapter.java:140) ~[?:?]
20.09 16:25:29 [Server] [INFO] at com.bgsoftware.wildstacker.utils.entity.EntityUtils.spawnExp(EntityUtils.java:152) ~[?:?]
20.09 16:25:29 [Server] [INFO] at com.bgsoftware.wildstacker.utils.entity.logic.DeathSimulation.lambda$null$3(DeathSimulation.java:209) ~[?:?]
20.09 16:25:29 [Server] [INFO] at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:60) ~[server.jar:1_8_R3]
20.09 16:25:29 [Server] [INFO] at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:355) [server.jar:1_8_R3]
20.09 16:25:29 [Server] [INFO] at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:965) [server.jar:1_8_R3]
20.09 16:25:29 [Server] [INFO] at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:371) [server.jar:1_8_R3]
20.09 16:25:29 [Server] [INFO] at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:870) [server.jar:1_8_R3]
20.09 16:25:29 [Server] [INFO] at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:760) [server.jar:1_8_R3]
20.09 16:25:29 [Server] [INFO] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]

**Comment by OmerBenGera** [comment] 2022-09-21 05:24
Duplicate of #473

**Closed by OmerBenGera** 2022-09-21 05:24 UTC
Labels: Pending
